import IntegralTopicArticle from '../../../components/public/IntegralTopicArticle';

const title = 'Belirli İntegral Nedir? Özellikleri ve Çözümlü Örnekler';
const description = 'Belirli integralin tanımını, temel teoremini ve sınırlarla işlem yapmayı adım adım çözümlü örneklerle öğrenin.';
export const metadata = {
  title, description, alternates: { canonical: '/makaleler/belirli-integral-nedir' },
  keywords: ['belirli integral nedir', 'belirli integral özellikleri', 'integralin temel teoremi', 'AYT matematik'],
  openGraph: { title, description, type: 'article', locale: 'tr_TR', siteName: 'MatAI', url: '/makaleler/belirli-integral-nedir', images: [{ url: '/assets/articles/integral-alan.jpg', width: 1536, height: 1024, alt: title }], publishedTime: '2026-08-12T00:00:00+03:00', modifiedTime: '2026-08-12T00:00:00+03:00', authors: ['MatAI'] },
  twitter: { card: 'summary_large_image', title, description, images: ['/assets/articles/integral-alan.jpg'] },
};
const article = { slug: 'belirli-integral-nedir', title, shortTitle: 'Belirli İntegral', description, summary: 'Alt ve üst sınırların ne anlattığını, integralin temel teoremini ve belirli integral sorularının çözümünü örneklerle öğrenin.', readingTime: 8, level: 'Temel konu anlatımı', keywords: ['belirli integral nedir', 'belirli integral özellikleri', 'integralin temel teoremi', 'AYT matematik'], toc: [{ id: 'tanim', label: 'Tanımı' }, { id: 'teorem', label: 'Temel teorem' }, { id: 'ozellikler', label: 'Özellikler' }, { id: 'ornekler', label: 'Çözümlü örnekler' }, { id: 'hatalar', label: 'Sık hatalar' }], intro: ['Belirli integral, bir fonksiyonun iki nokta arasındaki birikimini veya işaretli alanını tek bir sayı olarak verir. Belirsiz integralden farklı olarak sonuçta C sabiti bulunmaz.', 'a alt sınırı, b üst sınırı gösterir. Hesaplama için önce bir ilkel fonksiyon bulur, ardından üst sınırdaki değerden alt sınırdaki değeri çıkarırız.'], seriesLinks: [{ slug: 'belirsiz-integral-nedir', title: 'Belirsiz İntegral' }, { slug: 'integralde-degisken-degistirme', title: 'Değişken Değiştirme' }], related: { slug: 'integral-ile-alan-hesabi', title: 'İntegral ile Alan Hesabı', text: 'Grafiklerde geometrik alanı hesaplayın' } };
export default function DefiniteIntegralArticlePage() { return <IntegralTopicArticle article={article}>
  <section id="tanim"><h2>Belirli İntegralin Tanımı</h2><p>[a, b] aralığında sürekli bir f fonksiyonunun belirli integrali, çok küçük aralıkların katkılarının toplamının limitidir.</p><div className="article-math">∫<sub>a</sub><sup>b</sup> f(x) dx</div><p>Bu değer her zaman geometrik alan değildir; x ekseninin altındaki bölgeler toplama negatif katkı yapar.</p></section>
  <section id="teorem"><h2>İntegralin Temel Teoremi</h2><p>F&apos;(x) = f(x) ise belirli integral, ilkel fonksiyonun sınır değerleri arasındaki farkla bulunur.</p><div className="article-math">∫<sub>a</sub><sup>b</sup> f(x) dx = F(b) − F(a)</div><p>Kısa gösterimle [F(x)]<sub>a</sub><sup>b</sup> yazılır. Önce üst, sonra alt sınır kullanılır.</p></section>
  <section id="ozellikler"><h2>Temel Özellikler</h2><div className="article-math article-math-lines"><span>∫<sub>a</sub><sup>a</sup> f(x) dx = 0</span><span>∫<sub>a</sub><sup>b</sup> f(x) dx = −∫<sub>b</sub><sup>a</sup> f(x) dx</span><span>∫<sub>a</sub><sup>b</sup> f + ∫<sub>b</sub><sup>c</sup> f = ∫<sub>a</sub><sup>c</sup> f</span></div><p>Sınırlar aynıysa aralık yoktur. Sınırların yeri değiştiğinde ise işaret değişir.</p></section>
  <section id="ornekler"><h2>Adım Adım Çözümlü Örnek</h2><p>∫<sub>0</sub><sup>2</sup> (3x² + 1) dx integralinde ilkel fonksiyon x³ + x&apos;tir.</p><div className="article-math article-math-lines"><span>[x³ + x]<sub>0</sub><sup>2</sup></span><span>= (2³ + 2) − (0³ + 0) = 10</span></div><p>Belirsiz integral alırken yazılan C sabiti iki sınır değerinde birbirini götürdüğü için belirli integral sonucuna eklenmez.</p></section>
  <section id="hatalar"><h2>Sık Yapılan Hatalar</h2><p>Alt sınırdaki değeri çıkarmayı, parantez kullanmayı veya sınırlar ters çevrildiğinde işareti değiştirmeyi unutmak sık görülür. Sonuç bir alan sorusuna aitse fonksiyonun işaretini ayrıca incelemek gerekir.</p></section>
 </IntegralTopicArticle>; }
