import Link from 'next/link';
import IntegralTopicArticle from '../../../components/public/IntegralTopicArticle';

const title = 'İntegralde Değişken Değiştirme Yöntemi ve Örnekler';
const description = 'İntegralde değişken değiştirme yöntemini ne zaman ve nasıl kullanacağınızı adım adım çözümlü örneklerle öğrenin.';
export const metadata = {
  title, description, alternates: { canonical: '/makaleler/integralde-degisken-degistirme' },
  keywords: ['integralde değişken değiştirme', 'u dönüşümü', 'integral çözüm yöntemleri', 'AYT integral'],
  openGraph: { title, description, type: 'article', locale: 'tr_TR', siteName: 'MatAI', url: '/makaleler/integralde-degisken-degistirme', images: [{ url: '/assets/articles/integral-alan.jpg', width: 1536, height: 1024, alt: title }], publishedTime: '2026-08-12T00:00:00+03:00', modifiedTime: '2026-08-12T00:00:00+03:00', authors: ['MatAI'] },
  twitter: { card: 'summary_large_image', title, description, images: ['/assets/articles/integral-alan.jpg'] },
};
const article = { slug: 'integralde-degisken-degistirme', title, shortTitle: 'Değişken Değiştirme', description, summary: 'Karmaşık görünen bir integrali doğru değişken seçimiyle nasıl temel bir integrale dönüştürebileceğinizi adım adım inceleyelim.', readingTime: 8, level: 'Çözüm yöntemi', keywords: ['integralde değişken değiştirme', 'u dönüşümü', 'integral örnekleri', 'AYT integral'], toc: [{ id: 'mantik', label: 'Yöntemin mantığı' }, { id: 'secim', label: 'u nasıl seçilir?' }, { id: 'ornekler', label: 'Çözümlü örnekler' }, { id: 'sinirlar', label: 'Belirli integral' }, { id: 'hatalar', label: 'Sık hatalar' }], intro: ['Değişken değiştirme, zincir kuralını ters yönde kullanmaktır. İntegralin içindeki bir ifadeyi yeni bir değişkenle adlandırarak hem ifadeyi hem de diferansiyeli sadeleştiririz.', 'Özellikle bir bileşke fonksiyonla onun iç fonksiyonunun türevi aynı ifadede bulunuyorsa bu yöntem güçlü bir ilk seçenektir.'], related: { slug: 'belirli-integral-nedir', title: 'Belirli İntegral Nedir?', text: 'Sınırlar ve net değişim fikrine geçin' } };

export default function SubstitutionArticlePage() { return <IntegralTopicArticle article={article}>
  <section id="mantik"><h2>Değişken Değiştirmenin Mantığı</h2><p>g(x) ifadesini u olarak seçtiğimizde du = g&apos;(x) dx olur. Böylece x&apos;e bağlı karmaşık ifade, u&apos;ya bağlı daha basit bir integrale dönüşür.</p><div className="article-math">∫ f(g(x)) · g&apos;(x) dx = ∫ f(u) du</div><p>İşlem bittikten sonra u yerine yeniden seçtiğimiz g(x) ifadesini yazarız.</p></section>
  <section id="secim"><h2>u Değişkeni Nasıl Seçilir?</h2><p>Genellikle parantez içini, kökün içini, üstel fonksiyonun üssünü veya logaritmanın içini seçmek işe yarar. Kontrol sorusu şudur: <strong>Seçtiğim ifadenin türevi integrandın kalanında var mı?</strong></p><div className="article-math">∫ 2x·(x² + 1)⁵ dx &nbsp; için &nbsp; u = x² + 1</div></section>
  <section id="ornekler"><h2>Adım Adım Çözümlü Örnekler</h2><p><strong>Örnek 1:</strong> u = x² + 1 seçersek du = 2x dx olur.</p><div className="article-math article-math-lines"><span>∫ 2x·(x² + 1)⁵ dx = ∫ u⁵ du</span><span>= u⁶/6 + C = (x² + 1)⁶/6 + C</span></div><p><strong>Örnek 2:</strong> ∫ cos(3x) dx için u = 3x, du = 3 dx ve dx = du/3&apos;tür.</p><div className="article-math">∫ cos(3x) dx = ⅓∫ cos(u) du = ⅓sin(3x) + C</div></section>
  <section id="sinirlar"><h2>Belirli İntegralde Sınırlar</h2><p>Belirli integralde iki yol vardır: İntegrali çözdükten sonra x&apos;e dönmek veya u seçimiyle birlikte alt ve üst sınırları da u cinsine çevirmek. Sınırlar dönüştürüldüyse işlem sonunda tekrar x&apos;e dönülmez.</p><div className="article-math">x = a → u = g(a) &nbsp;&nbsp; | &nbsp;&nbsp; x = b → u = g(b)</div></section>
  <section id="hatalar"><h2>Sık Yapılan Hatalar</h2><p>Yalnızca parantezi u ile değiştirip dx&apos;i dönüştürmemek en yaygın hatadır. Sabit çarpan eksikse onu dengelemek ve belirli integralde sınırları hangi değişkene ait olduklarıyla birlikte takip etmek gerekir.</p><p>Temel integral kurallarında eksiğiniz varsa önce <Link className="article-inline-link" href="/makaleler/belirsiz-integral-nedir">belirsiz integral yazısını</Link> okuyabilirsiniz.</p></section>
 </IntegralTopicArticle>; }
