export const derivativeArticles = [
  {
    slug: 'turev-nedir', shortTitle: 'Türev Nedir?', title: 'Türev Nedir? Temel Kurallar ve Çözümlü Örnekler',
    description: 'Türevin ne olduğunu, limit ile tanımını ve temel türev kurallarını adım adım çözümlü örneklerle öğrenin.',
    summary: 'Türevi yalnızca bir formül olarak değil, anlık değişim hızı ve teğet eğimi olarak anlayıp temel örneklerle uygulayın.',
    readingTime: 9, level: 'Temel konu anlatımı', symbol: 'f′', formula: 'lim Δx→0',
    keywords: ['türev nedir', 'türev konu anlatımı', 'temel türev kuralları', 'AYT matematik'],
    intro: ['Türev, bir niceliğin başka bir niceliğe göre anlık değişim hızını ölçer. Bir aracın belirli andaki hızı veya bir eğrinin tek bir noktadaki eğimi aynı düşüncenin farklı örnekleridir.', 'Konuyu sağlam öğrenmenin yolu formülleri ezberlemekten önce türevin neyi ölçtüğünü anlamaktır.'],
    sections: [
      ['anlam', 'Türev Ne Anlama Gelir?', ['y = f(x) fonksiyonunda x çok küçük bir miktar değiştiğinde f(x) değerinin ne kadar değiştiğini inceleriz. Ortalama değişim oranının aralığı sıfıra yaklaştırıldığında anlık değişim oranına ulaşılır.'], ['f′(x) = lim(h→0) [f(x+h) − f(x)] / h']],
      ['gosterim', 'Türev Gösterimleri', ['Aynı türev farklı biçimlerde gösterilebilir. Soruda kullanılan gösterim değişse de hepsi fonksiyonun x değişkenine göre türevini ifade eder.'], ['f′(x) = y′ = dy/dx = d/dx[f(x)]']],
      ['kurallar', 'Temel Türev Kuralları', ['Sabitin türevi sıfırdır. Kuvvet kuralında üs başa katsayı olarak gelir ve bir azalır. Toplamın türevi terimlerin türevleri toplamıdır.'], ['d/dx(c) = 0', 'd/dx(xⁿ) = n·xⁿ⁻¹', '(f ± g)′ = f′ ± g′']],
      ['ornekler', 'Çözümlü Örnekler', ['f(x) = 3x⁴ − 2x² + 5 için her terimin türevini ayrı alırız. Sabit 5 kaybolur.', 'g(x) = √x ifadesini x¹ᐟ² biçiminde yazıp kuvvet kuralını uygularız.'], ['f′(x) = 12x³ − 4x', 'g′(x) = ½x⁻¹ᐟ² = 1/(2√x)']],
      ['kontrol', 'Sonucu Nasıl Kontrol Ederiz?', ['Türev sonucundaki üslerin genellikle bir azaldığını ve sabitlerin kaybolduğunu kontrol edin. Belirsiz integral ile türev ters işlemlerdir; bu ilişki iki konuyu birlikte öğrenmeyi kolaylaştırır.'], []],
    ],
    related: { slug: 'turev-alma-kurallari', title: 'Türev Alma Kuralları', text: 'Çarpım, bölüm ve zincir kuralına geçin' },
  },
  {
    slug: 'turev-alma-kurallari', shortTitle: 'Türev Alma Kuralları', title: 'Türev Alma Kuralları: Çarpım, Bölüm ve Zincir Kuralı',
    description: 'Çarpım, bölüm ve zincir kuralını hangi durumlarda kullanacağınızı çözümlü türev örnekleriyle öğrenin.',
    summary: 'Birden fazla fonksiyonun birlikte bulunduğu ifadelerde doğru türev kuralını seçmeyi ve işlemi hatasız yürütmeyi öğrenin.',
    readingTime: 10, level: 'Çözüm yöntemleri', symbol: 'd/dx', formula: '(f∘g)′', keywords: ['türev alma kuralları', 'çarpım kuralı', 'bölüm kuralı', 'zincir kuralı'],
    intro: ['Temel kuvvet kuralı her ifadeyi tek başına çözmeye yetmez. Fonksiyonlar çarpım, bölüm veya bileşke hâlindeyse yapıya uygun bir kural seçmek gerekir.', 'Kural seçiminden önce ifadeyi sadeleştirmek bazen işlemi ciddi ölçüde kısaltır.'],
    sections: [
      ['carpim', 'Çarpım Kuralı', ['İki fonksiyon çarpılıyorsa birinciyi sabit tutup ikincinin türevini, sonra ikinciyi sabit tutup birincinin türevini alırız.'], ['(f·g)′ = f′·g + f·g′', 'd/dx[x²·sin x] = 2x·sin x + x²·cos x']],
      ['bolum', 'Bölüm Kuralı', ['Payın türevi çarpı payda eksi pay çarpı paydanın türevi yazılır; tamamı paydanın karesine bölünür.'], ['(f/g)′ = (f′g − fg′) / g²', 'd/dx[(x+1)/x] = [x − (x+1)]/x² = −1/x²']],
      ['zincir', 'Zincir Kuralı', ['Bir fonksiyon başka bir fonksiyonun içindeyse dış fonksiyonun türevi alınır ve iç fonksiyonun türeviyle çarpılır.'], ['d/dx[f(g(x))] = f′(g(x))·g′(x)', 'd/dx[(3x²+1)⁵] = 5(3x²+1)⁴·6x']],
      ['secim', 'Hangi Kuralı Seçmeliyim?', ['Çarpım işareti varsa çarpım, kesir yapısı varsa bölüm, parantezin kuvveti veya bir fonksiyonun içinde başka fonksiyon varsa zincir kuralını düşünün. Aynı soruda birden fazla kural birlikte kullanılabilir.'], []],
      ['hatalar', 'Sık Yapılan Hatalar', ['Çarpımın türevini yalnızca türevlerin çarpımı sanmak, bölüm kuralındaki sırayı değiştirmek ve zincir kuralında iç türevi unutmak en yaygın hatalardır.'], ['(f·g)′ ≠ f′·g′']],
    ],
    related: { slug: 'turevin-geometrik-yorumu', title: 'Türevin Geometrik Yorumu', text: 'Türevin grafik üzerindeki anlamını görün' },
  },
  {
    slug: 'turevin-geometrik-yorumu', shortTitle: 'Türevin Geometrik Yorumu', title: 'Türevin Geometrik Yorumu: Teğet Eğimi ve Anlık Değişim',
    description: 'Türevin geometrik anlamını, teğet eğimini ve bir noktadaki anlık değişim hızını çözümlü örneklerle öğrenin.',
    summary: 'Sekant doğrusundan teğete geçişi, türev değerinin grafikte ne anlattığını ve teğet denklemini birlikte inceleyin.',
    readingTime: 8, level: 'Geometrik yorum', symbol: 'm', formula: 'm = f′(a)', keywords: ['türevin geometrik yorumu', 'teğet eğimi', 'anlık değişim hızı', 'teğet denklemi'],
    intro: ['Türev, bir fonksiyonun grafiğine belirli bir noktada çizilen teğetin eğimidir. Pozitif türev yükselen, negatif türev alçalan bir yönü gösterir.', 'Bu yorum türevi grafik, hareket ve optimizasyon problemlerine bağlayan temel köprüdür.'],
    sections: [
      ['sekant', 'Sekanttan Teğete', ['Grafik üzerindeki iki noktayı birleştiren sekantın eğimi ortalama değişim oranıdır. İkinci nokta birinciye yaklaştıkça sekant doğrusu teğete yaklaşır.'], ['m(sekant) = [f(a+h) − f(a)] / h', 'm(teğet) = f′(a)']],
      ['teget', 'Teğet Denklemi', ['x = a noktasında eğim f′(a), teğme noktası (a, f(a)) olur. Nokta-eğim formu ile doğru denklemi yazılır.'], ['y − f(a) = f′(a)(x − a)']],
      ['ornek', 'Çözümlü Teğet Örneği', ['f(x) = x² eğrisine x = 2 noktasında çizilen teğeti bulalım. f′(x) = 2x olduğundan eğim 4, teğme noktası (2, 4) olur.'], ['y − 4 = 4(x − 2)', 'y = 4x − 4']],
      ['normal', 'Normal Doğrusu', ['Teğete dik olan doğruya normal denir. Sıfırdan farklı teğet eğimi m ise normalin eğimi −1/m olur.'], ['m(teğet) · m(normal) = −1']],
      ['yorum', 'Türev Değerini Yorumlama', ['f′(a) = 0 ise teğet yataydır; fakat bu tek başına maksimum veya minimum olduğunu kanıtlamaz. İşaret değişimi ayrıca incelenmelidir.'], []],
    ],
    related: { slug: 'artan-azalan-fonksiyonlar', title: 'Artan ve Azalan Fonksiyonlar', text: 'Türevin işaretiyle grafiğin yönünü belirleyin' },
  },
  {
    slug: 'artan-azalan-fonksiyonlar', shortTitle: 'Artan ve Azalan Fonksiyonlar', title: 'Artan ve Azalan Fonksiyonlar Türevle Nasıl Bulunur?',
    description: 'Bir fonksiyonun artan ve azalan olduğu aralıkları türevin işaret tablosuyla adım adım belirlemeyi öğrenin.',
    summary: 'Kritik noktaları bulup türevin işaretini inceleyerek fonksiyonun hangi aralıklarda yükseldiğini veya düştüğünü belirleyin.',
    readingTime: 8, level: 'Fonksiyon analizi', symbol: '↗↘', formula: 'f′(x) ≷ 0', keywords: ['artan azalan fonksiyonlar', 'türev işaret tablosu', 'kritik nokta', 'AYT türev'],
    intro: ['Türev pozitifken fonksiyon artar, negatifken azalır. Bu basit ilişki grafik yorumlama ve ekstremum sorularının temelidir.', 'İşaret tablosu hazırlarken fonksiyonun tanım kümesi ve türevin sıfır ya da tanımsız olduğu noktalar birlikte değerlendirilir.'],
    sections: [
      ['kural', 'Artma ve Azalma Kuralı', ['Bir aralıkta f′(x) > 0 ise f artan, f′(x) < 0 ise f azalandır. Türevin sıfır olması yalnızca kritik nokta adayı verir.'], ['f′(x) > 0 ⇒ f artan', 'f′(x) < 0 ⇒ f azalan']],
      ['kritik', 'Kritik Noktalar Nasıl Bulunur?', ['Önce f′(x) hesaplanır. Türevi sıfır yapan veya türevin tanımsız olduğu, fakat fonksiyonun tanımlı kaldığı x değerleri işaret tablosunu böler.'], []],
      ['tablo', 'İşaret Tablosu', ['Kritik noktaların ayırdığı her aralıktan bir test değeri seçilir. Bu değer türevde yerine yazılarak işaret bulunur ve artma-azalma yönleri tabloya yerleştirilir.'], []],
      ['ornek', 'Çözümlü Örnek', ['f(x) = x³ − 3x için f′(x) = 3x² − 3 = 3(x−1)(x+1) olur. Kritik noktalar −1 ve 1’dir.'], ['(−∞,−1): artan', '(−1,1): azalan', '(1,∞): artan']],
      ['hatalar', 'Sık Yapılan Hatalar', ['Fonksiyonun değil türevin işaretine bakıldığını unutmayın. Kritik noktaları doğrudan artan veya azalan aralığa dahil etmek yerine sorudaki aralık tanımına dikkat edin.'], []],
    ],
    related: { slug: 'turevde-maksimum-minimum', title: 'Türevde Maksimum ve Minimum', text: 'İşaret değişiminden ekstremumları bulun' },
  },
  {
    slug: 'turevde-maksimum-minimum', shortTitle: 'Maksimum ve Minimum', title: 'Türevde Maksimum ve Minimum Problemleri',
    description: 'Yerel maksimum ve minimum noktalarını türevle bulmayı ve optimizasyon problemlerini adım adım çözmeyi öğrenin.',
    summary: 'Kritik noktaları, türev işaret değişimini ve problem koşullarını kullanarak en büyük ve en küçük değerleri bulun.',
    readingTime: 10, level: 'Optimizasyon', symbol: 'max', formula: 'f′(x)=0', keywords: ['türev maksimum minimum', 'optimizasyon problemleri', 'yerel ekstremum', 'AYT matematik'],
    intro: ['Maksimum-minimum soruları bir niceliğin alabileceği en büyük veya en küçük değeri arar. Geometrik problemlerde alanı büyütmek, maliyeti azaltmak veya uzaklığı en aza indirmek bu yapıya örnektir.', 'Her f′(x) = 0 noktası ekstremum değildir; türevin noktanın iki yanında nasıl işaret değiştirdiği kontrol edilmelidir.'],
    sections: [
      ['yerel', 'Yerel Ekstremum Nedir?', ['Türev pozitiften negatife geçerse yerel maksimum, negatiften pozitife geçerse yerel minimum oluşur. İşaret değişmiyorsa yatay teğet vardır fakat ekstremum olmayabilir.'], ['+ → − : yerel maksimum', '− → + : yerel minimum']],
      ['adimlar', 'Optimizasyon Adımları', ['İstenen niceliği bir değişkene bağlı fonksiyon olarak yazın. Tanım aralığını belirleyin, türevi sıfıra eşitleyin ve kritik noktalarla uç noktaları karşılaştırın.'], []],
      ['ornek', 'Çözümlü Geometri Örneği', ['Çevresi 20 birim olan dikdörtgende kenarlar x ve 10−x olur. Alan A(x) = x(10−x)’tir.'], ['A(x) = 10x − x²', 'A′(x) = 10 − 2x = 0 ⇒ x = 5', 'En büyük alan = 5·5 = 25']],
      ['ikinci', 'İkinci Türev Testi', ['f′(a)=0 iken f″(a)<0 ise grafik aşağı kıvrılır ve yerel maksimum; f″(a)>0 ise yukarı kıvrılır ve yerel minimum vardır.'], ['f″(a) < 0 ⇒ maksimum', 'f″(a) > 0 ⇒ minimum']],
      ['hatalar', 'Problem Sorularında Kontrol', ['Bulduğunuz değerin problemdeki tanım aralığında olmasına ve sorunun x değerini mi yoksa maksimum-minimum fonksiyon değerini mi istediğine dikkat edin.'], []],
    ],
    related: { slug: 'turev-ile-grafik-cizimi', title: 'Türev ile Grafik Çizimi', text: 'Fonksiyon analizini tam bir grafiğe dönüştürün' },
  },
  {
    slug: 'turev-ile-grafik-cizimi', shortTitle: 'Türev ile Grafik Çizimi', title: 'Türev ile Grafik Çizimi ve Fonksiyon Analizi',
    description: 'Tanım kümesi, kritik noktalar, artma-azalma ve ikinci türev bilgileriyle fonksiyon grafiğini adım adım çizin.',
    summary: 'Bir fonksiyonun cebirsel ifadesinden grafik davranışına geçmek için gereken türev tabanlı kontrol listesini uygulayın.',
    readingTime: 10, level: 'Grafik analizi', symbol: '⌁', formula: 'f′, f″', keywords: ['türev ile grafik çizimi', 'fonksiyon analizi', 'konkavlık', 'büküm noktası'],
    intro: ['Türev, grafiğin yalnızca tek bir noktadaki eğimini değil bütün davranışını anlamamızı sağlar. Artma-azalma, ekstremum ve kıvrım bilgileri birleştiğinde grafiğin iskeleti ortaya çıkar.', 'Doğru sıra ile yapılan analiz, karmaşık görünen grafik sorularını düzenli bir kontrol listesine dönüştürür.'],
    sections: [
      ['hazirlik', 'Grafikten Önce Cebirsel Hazırlık', ['Tanım kümesini, eksen kesişimlerini, simetriyi ve varsa düşey-yatay asimptotları belirleyin. Bu bilgiler grafiğin geçebileceği bölgeleri sınırlar.'], []],
      ['birinci', 'Birinci Türev Analizi', ['f′(x)=0 veya tanımsız olan kritik noktaları bulun. İşaret tablosu ile artan-azalan aralıkları ve yerel ekstremumları belirleyin.'], []],
      ['ikinci', 'İkinci Türev ve Konkavlık', ['f″(x)>0 iken grafik yukarı, f″(x)<0 iken aşağı konkavdır. İkinci türevin işaret değiştirdiği ve fonksiyonun tanımlı olduğu nokta büküm noktasıdır.'], ['f″(x) > 0 ⇒ yukarı konkav', 'f″(x) < 0 ⇒ aşağı konkav']],
      ['ornek', 'Örnek Analiz', ['f(x)=x³−3x fonksiyonunun kritik noktaları −1 ve 1’dir. Yerel maksimum (−1,2), yerel minimum (1,−2) olur. f″(x)=6x işaretini x=0’da değiştirdiği için (0,0) büküm noktasıdır.'], []],
      ['kontrol', 'Grafik Çizim Kontrol Listesi', ['Tanım kümesi, kesişimler, limit ve asimptotlar, kritik noktalar, artma-azalma, ekstremumlar, konkavlık ve büküm noktalarını aynı koordinat sisteminde birleştirin.'], []],
    ],
    related: { slug: 'turev-sorusu-nasil-cozulur', title: 'Türev Sorusu Nasıl Çözülür?', text: 'Soru türüne göre yöntem seçimini öğrenin' },
  },
  {
    slug: 'turev-sorusu-nasil-cozulur', shortTitle: 'Türev Sorusu Çözümü', title: 'Türev Sorusu Nasıl Çözülür? Adım Adım Strateji',
    description: 'Türev sorularında verilenleri yorumlamayı, doğru yöntemi seçmeyi ve sonucu kontrol etmeyi örneklerle öğrenin.',
    summary: 'Kural, teğet, artma-azalma, ekstremum ve grafik sorularını ayırt ederek doğru çözüm yoluna daha hızlı ulaşın.',
    readingTime: 9, level: 'Soru çözüm stratejisi', symbol: '?′', formula: 'verilen → yöntem', keywords: ['türev sorusu nasıl çözülür', 'türev soru çözümü', 'AYT türev taktikleri', 'türev yöntemleri'],
    intro: ['Türev sorularında en zor bölüm çoğu zaman işlemi yapmak değil, sorunun hangi bilgiyi istediğini fark etmektir. “Eğim”, “artan”, “en büyük” ve “anlık hız” ifadeleri farklı çözüm yollarını işaret eder.', 'Soruyu küçük bir karar ağacıyla sınıflandırmak hem süreyi hem işlem hatalarını azaltır.'],
    sections: [
      ['oku', 'Sorudaki Anahtar İfadeyi Bulun', ['Teğet veya eğim deniyorsa f′(a), artan-azalan deniyorsa f′ işareti, maksimum-minimum deniyorsa kritik noktalar, hız deniyorsa konum fonksiyonunun türevi düşünülür.'], []],
      ['sadeles', 'Türevden Önce Sadeleştirin', ['Kesirleri üs biçiminde yazmak, ortak çarpan almak veya özdeşlik kullanmak uzun bölüm ve çarpım işlemlerini kısaltabilir.'], ['(x²+x)/x = x+1 &nbsp; (x≠0)']],
      ['ornek', 'Adım Adım Örnek', ['f(x)=(x²+1)³ için x=1 noktasındaki teğet eğimi sorulsun. Bileşke yapı nedeniyle zincir kuralını kullanırız.'], ['f′(x)=3(x²+1)²·2x', 'f′(1)=6·(2)²=24']],
      ['kontrol', 'Sonucu Kontrol Edin', ['İstenen şeyin türev fonksiyonu mu, belirli noktadaki eğim mi, koordinat mı yoksa maksimum değer mi olduğunu yeniden okuyun. Tanım kümesini ve işaretleri kontrol edin.'], []],
      ['plan', 'Sınav İçin Çalışma Planı', ['Önce temel kuralları, sonra karışık kural seçimini; ardından teğet, artma-azalma, ekstremum ve grafik uygulamalarını sırayla çalışın. Her yanlışta hatanın kural mı yorum mu olduğunu not edin.'], []],
    ],
    related: { slug: 'turevde-sik-yapilan-hatalar', title: 'Türevde Sık Yapılan Hatalar', text: 'Puan kaybettiren ayrıntıları gözden geçirin' },
  },
  {
    slug: 'turevde-sik-yapilan-hatalar', shortTitle: 'Türevde Sık Hatalar', title: 'Türevde Sık Yapılan Hatalar ve Doğru Çözümleri',
    description: 'Türev sorularında en sık yapılan kural, işaret, zincir ve yorum hatalarını doğru çözümleriyle inceleyin.',
    summary: 'Küçük görünen fakat sonucu tamamen değiştiren türev hatalarını örnekler ve kontrol yöntemleriyle ortadan kaldırın.',
    readingTime: 8, level: 'Tekrar ve pekiştirme', symbol: '✓', formula: 'hata → doğru', keywords: ['türevde sık yapılan hatalar', 'türev yanlışları', 'zincir kuralı hataları', 'AYT türev'],
    intro: ['Türevde yanlışların önemli bölümü bilgi eksikliğinden değil, ifadenin yapısını yanlış okumaktan kaynaklanır. Özellikle zincir ve çarpım kuralları küçük unutmalara açıktır.', 'Her çözümün sonunda uygulanacak kısa bir kontrol listesi bu hataların çoğunu sınavdan önce yakalar.'],
    sections: [
      ['kuvvet', 'Kuvvet Kuralında Üs Hatası', ['Üs başa gelirken bir azaltılır; üs ile katsayının yer değiştirmesi veya üssün değişmeden bırakılması yanlıştır.'], ['d/dx(4x³) = 12x²']],
      ['carpim', 'Çarpımın Türevini Yanlış Almak', ['İki fonksiyonun türevi ayrı ayrı alınıp çarpılmaz. Çarpım kuralında iki terimli toplam oluşur.'], ['(f·g)′ = f′g + fg′']],
      ['zincir', 'İç Fonksiyonun Türevini Unutmak', ['(2x+1)⁵ ifadesinin türevi yalnızca 5(2x+1)⁴ değildir; içteki 2x+1’in türevi olan 2 ile de çarpılır.'], ['d/dx[(2x+1)⁵] = 10(2x+1)⁴']],
      ['yorum', 'f(a) ile f′(a) Değerlerini Karıştırmak', ['f(a) grafikte noktanın y koordinatını, f′(a) ise o noktadaki teğet eğimini verir. Teğet denkleminde ikisine de ihtiyaç duyulur.'], []],
      ['kontrol', 'Beş Maddelik Son Kontrol', ['İfadeyi sadeleştirdim mi? Doğru kuralı seçtim mi? İç türevi aldım mı? İşaret ve parantezler doğru mu? Sorunun istediği değeri mi buldum?'], []],
    ],
    related: { slug: 'turev-nedir', title: 'Türev Nedir?', text: 'Temelden başlayarak konu zincirini tekrar edin' },
  },
  {
    slug: 'trigonometrik-fonksiyonlarin-turevi', shortTitle: 'Trigonometrik Türevler', title: 'Trigonometrik Fonksiyonların Türevi ve Çözümlü Örnekler',
    description: 'Sinüs, kosinüs ve diğer trigonometrik fonksiyonların türevlerini zincir kuralıyla birlikte çözümlü örneklerle öğrenin.',
    publishedAt: '2026-08-19',
    summary: 'Temel trigonometrik türevleri ezberlemekle kalmayın; işaretlerin nereden geldiğini ve bileşke ifadelerde zincir kuralını nasıl kullanacağınızı görün.',
    readingTime: 9, level: 'Kural ve uygulama', symbol: 'sin′', formula: '(sin x)′ = cos x', keywords: ['trigonometrik fonksiyonların türevi', 'sinüs türevi', 'kosinüs türevi', 'trigonometrik türevler'],
    intro: ['Trigonometrik fonksiyonların türevleri özellikle limit, hareket ve periyodik değişim problemlerinde sık kullanılır. Temel altı fonksiyonun türevini bilmek işlemi hızlandırır.', 'Açı yalnızca x değil de başka bir ifade olduğunda zincir kuralı devreye girer. Bu ayrım, trigonometrik türev sorularındaki en önemli kontrol noktasıdır.'],
    sections: [
      ['temel', 'Sinüs ve Kosinüsün Türevi', ['Sinüsün türevi kosinüs, kosinüsün türevi ise negatif sinüstür. Kosinüs türevindeki eksi işareti en sık unutulan ayrıntıdır.'], ['(sin x)′ = cos x', '(cos x)′ = −sin x']],
      ['diger', 'Diğer Trigonometrik Türevler', ['Tanjant ve kotanjantın türevleri ikinci kuvvetli; sekant ve kosekantın türevleri ise iki trigonometrik fonksiyonun çarpımı biçimindedir.'], ['(tan x)′ = sec²x', '(cot x)′ = −csc²x', '(sec x)′ = sec x·tan x', '(csc x)′ = −csc x·cot x']],
      ['zincir', 'Zincir Kuralıyla Trigonometrik Türev', ['İçeride u(x) varsa önce dış trigonometrik fonksiyonun türevi alınır, ardından u′(x) ile çarpılır.'], ['d/dx[sin(u)] = cos(u)·u′', 'd/dx[cos(3x²)] = −sin(3x²)·6x']],
      ['ornek', 'Çözümlü Örnek', ['f(x)=x²·sin x ifadesinde çarpım kuralı gerekir. Birinci çarpanın türevi ile ikinci, ardından birinci ile ikincinin türevi çarpılıp toplanır.'], ['f′(x) = 2x·sin x + x²·cos x']],
      ['hatalar', 'İşaret ve Açı Birimi Kontrolü', ['Standart türev formülleri açı radyan cinsindeyken geçerlidir. Ayrıca cos türevindeki eksi işaretini ve bileşke ifadelerde iç türevi kontrol edin.'], []],
    ],
    related: { slug: 'ustel-ve-logaritmik-fonksiyonlarin-turevi', title: 'Üstel ve Logaritmik Fonksiyonların Türevi', text: 'Diğer özel fonksiyonların türevlerine geçin' },
  },
  {
    slug: 'ustel-ve-logaritmik-fonksiyonlarin-turevi', shortTitle: 'Üstel ve Logaritmik Türevler', title: 'Üstel ve Logaritmik Fonksiyonların Türevi',
    description: 'e üzeri x, a üzeri x ve logaritmik fonksiyonların türev kurallarını zincir kuralı ve örneklerle öğrenin.',
    publishedAt: '2026-08-19',
    summary: 'Üstel ve logaritmik ifadelerin temel türevlerini, tabanın sonucu nasıl etkilediğini ve logaritmik türev alma yöntemini uygulayın.',
    readingTime: 9, level: 'Kural ve uygulama', symbol: 'eˣ', formula: '(ln x)′ = 1/x', keywords: ['üstel fonksiyonun türevi', 'logaritmanın türevi', 'ln x türevi', 'logaritmik türev alma'],
    intro: ['Üstel fonksiyonlar büyüme ve azalma modellerinde, logaritmik fonksiyonlar ise bu süreçlerin tersini incelerken karşımıza çıkar. e tabanlı üstel fonksiyonun türevinin kendisine eşit olması bu konuyu özel kılar.', 'Taban e dışında olduğunda veya üs bileşke bir ifade içerdiğinde ek çarpanları dikkatle yazmak gerekir.'],
    sections: [
      ['ustel', 'Üstel Fonksiyonların Türevi', ['eˣ fonksiyonu türev alındığında değişmez. aˣ fonksiyonunda ise sonuç ln a ile çarpılır.'], ['(eˣ)′ = eˣ', '(aˣ)′ = aˣ·ln a']],
      ['logaritma', 'Logaritmik Fonksiyonların Türevi', ['Doğal logaritmanın türevi 1/x’tir. Farklı tabandaki logaritmada paydaya tabanın doğal logaritması eklenir.'], ['(ln x)′ = 1/x', '(logₐx)′ = 1/(x·ln a)']],
      ['zincir', 'Bileşke İfadeler', ['Üs veya logaritmanın içi x’ten farklıysa zincir kuralı uygulanır ve iç fonksiyonun türeviyle çarpılır.'], ['d/dx[e^(x²)] = 2x·e^(x²)', 'd/dx[ln(3x+1)] = 3/(3x+1)']],
      ['logturev', 'Logaritmik Türev Alma', ['Değişken hem tabanda hem üsteyse iki tarafın doğal logaritması alınabilir. y=xˣ için ln y=x ln x yazıp kapalı türev uygularız.'], ['y′/y = ln x + 1', 'y′ = xˣ(ln x + 1)']],
      ['tanim', 'Tanım Kümesini Unutmayın', ['Gerçel sayılarda ln(g(x)) ifadesi için g(x)>0 olmalıdır. Türev işleminden önce bu koşulu belirlemek, geçersiz sonuç aralıklarını önler.'], []],
    ],
    related: { slug: 'yuksek-mertebeden-turev', title: 'Yüksek Mertebeden Türev', text: 'İkinci ve daha yüksek türevleri inceleyin' },
  },
  {
    slug: 'yuksek-mertebeden-turev', shortTitle: 'Yüksek Mertebeden Türev', title: 'İkinci ve Yüksek Mertebeden Türev Nedir?',
    description: 'İkinci ve daha yüksek mertebeden türevlerin gösterimini, grafik yorumunu ve hareket problemlerindeki kullanımını öğrenin.',
    publishedAt: '2026-08-19',
    summary: 'Bir fonksiyonun türevini yeniden alarak değişimin nasıl değiştiğini; konkavlık, ivme ve büküm noktaları üzerinden yorumlayın.',
    readingTime: 8, level: 'İleri konu anlatımı', symbol: 'f″', formula: 'f⁽ⁿ⁾(x)', keywords: ['ikinci türev', 'yüksek mertebeden türev', 'konkavlık', 'ivme türev'],
    intro: ['Birinci türev fonksiyonun değişim hızını, ikinci türev ise bu değişim hızının nasıl değiştiğini gösterir. İşleme devam edilerek üçüncü ve daha yüksek mertebeden türevler elde edilir.', 'Yüksek mertebeden türevler grafik analizinde, hareket problemlerinde ve bazı dizi-formül sorularında güçlü bir araçtır.'],
    sections: [
      ['tanim', 'Yüksek Mertebeden Türev Gösterimi', ['f′ fonksiyonunun türevi f″, onun türevi f‴ olarak gösterilir. Genel n’inci türev için f⁽ⁿ⁾(x) yazımı kullanılır.'], ['f″(x) = d²y/dx²', 'f⁽ⁿ⁾(x) = dⁿy/dxⁿ']],
      ['ornek', 'Polinom Örneği', ['f(x)=x⁴−2x³+5 için art arda türev alalım. Polinomun derecesi her adımda bir azalır ve yeterince türev alındığında sonuç sıfır olur.'], ['f′(x)=4x³−6x²', 'f″(x)=12x²−12x', 'f‴(x)=24x−12', 'f⁽⁴⁾(x)=24']],
      ['grafik', 'İkinci Türev ve Konkavlık', ['f″ pozitifse eğimler artar ve grafik yukarı konkavdır; negatifse eğimler azalır ve grafik aşağı konkavdır. f″ değerinin işaret değiştirmesi büküm noktası için temel koşuldur.'], ['f″(x)>0 ⇒ yukarı konkav', 'f″(x)<0 ⇒ aşağı konkav']],
      ['hareket', 'Hız ve İvme İlişkisi', ['Konum s(t) ile verilmişse birinci türev hız, ikinci türev ivmedir. Böylece yüksek mertebeden türev fiziksel bir değişimi doğrudan açıklar.'], ['v(t)=s′(t)', 'a(t)=v′(t)=s″(t)']],
      ['kontrol', 'Büküm Noktası Kontrolü', ['Yalnızca f″(a)=0 olması büküm noktası için yeterli değildir. İkinci türevin a’nın iki yanında işaret değiştirip değiştirmediği incelenmelidir.'], []],
    ],
    related: { slug: 'turev-hareket-problemleri', title: 'Türevle Hareket Problemleri', text: 'Konum, hız ve ivme bilgisini problemlerde kullanın' },
  },
  {
    slug: 'turev-hareket-problemleri', shortTitle: 'Türevle Hareket Problemleri', title: 'Türevle Hareket Problemleri: Konum, Hız ve İvme',
    description: 'Konum fonksiyonundan hız ve ivme bulmayı, yön değiştirme ve toplam yol sorularını adım adım öğrenin.',
    publishedAt: '2026-08-19',
    summary: 'Konum, hız ve ivme arasındaki türev ilişkisini kurup parçacığın ne zaman durduğunu, yön değiştirdiğini ve aldığı yolu hesaplayın.',
    readingTime: 10, level: 'Problem uygulaması', symbol: 'v(t)', formula: 's → v → a', keywords: ['türev hareket problemleri', 'konum hız ivme', 'anlık hız', 'yön değiştirme'],
    intro: ['Hareket problemlerinde türev, zamana bağlı konum bilgisini hıza ve ivmeye dönüştürür. Sorunun verdiği fonksiyonun konum mu yoksa hız mı olduğunu doğru belirlemek ilk adımdır.', 'Yer değiştirme ile alınan toplam yol aynı değildir. Hızın işaret değiştirdiği anlar, toplam yolu hesaplarken hareketi parçalara ayırır.'],
    sections: [
      ['iliski', 'Konum, Hız ve İvme', ['s(t) konum fonksiyonuysa türevi anlık hızı verir. Hızın türevi, yani konumun ikinci türevi ise ivmedir.'], ['v(t)=s′(t)', 'a(t)=v′(t)=s″(t)']],
      ['durma', 'Parçacık Ne Zaman Durur?', ['Parçacık v(t)=0 olduğu anlarda durur. Ancak yön değiştirmesi için hızın bu anın iki yanında farklı işaretlere sahip olması gerekir.'], ['v(t)=0 ⇒ durma anı', 'v: + → − veya − → + ⇒ yön değişimi']],
      ['ornek', 'Çözümlü Hız ve İvme Örneği', ['s(t)=t³−6t²+9t için hız ve ivmeyi bulalım. Hızı sıfıra eşitlediğimizde durma anları t=1 ve t=3 çıkar.'], ['v(t)=3t²−12t+9=3(t−1)(t−3)', 'a(t)=6t−12']],
      ['yol', 'Toplam Yol Nasıl Bulunur?', ['Önce incelenen zaman aralığındaki yön değiştirme anlarını bulun. Her alt aralıktaki konum farkının mutlak değerini alıp sonuçları toplayın.'], ['Toplam yol = |Δs₁| + |Δs₂| + …']],
      ['yorum', 'Hızlanma ve Yavaşlama', ['Hız ile ivme aynı işaretliyse sürat artar, zıt işaretliyse sürat azalır. Burada hızın büyüklüğü olan sürat ile işaretli hız değerini ayırmak gerekir.'], ['v·a>0 ⇒ hızlanır', 'v·a<0 ⇒ yavaşlar']],
    ],
    related: { slug: 'turevde-maksimum-minimum', title: 'Türevde Maksimum ve Minimum', text: 'Hareketten optimizasyon problemlerine geçin' },
  },
];

export const derivativeArticleMap = Object.fromEntries(derivativeArticles.map((article) => [article.slug, article]));
