const guide = (data) => ({ readingTime: 9, ...data });

export const englishFoundationArticles = [
  guide({
    slug: 'what-is-a-limit', trSlug: 'limit-nedir', category: 'Limits & Continuity', symbol: 'lim', formula: 'x → a',
    title: 'What Is a Limit? Intuition and Worked Examples',
    description: 'Understand what a function approaches near a point using graphs, tables, algebra, and worked limit examples.',
    summary: 'A limit describes the value f(x) approaches as x approaches a point; it does not require f to have that value at the point.',
    sections: [
      { id: 'meaning', title: 'What a limit means', paragraphs: ['If f(x) approaches the same number L as x approaches a from both sides, the limit of f at a is L. The focus is nearby behavior, not merely substitution at one point.'], formulas: ['lim(x→a) f(x) = L'] },
      { id: 'value', title: 'Limit versus function value', paragraphs: ['The limit may exist even when f(a) is undefined or different from L. A hole in a graph can therefore have a perfectly well-defined limit.'] },
      { id: 'example', title: 'A worked algebraic example', paragraphs: ['Direct substitution gives 0/0, so factor the numerator and cancel the common factor for x values near 2.'], formulas: ['lim(x→2) (x²−4)/(x−2)', '= lim(x→2)(x+2) = 4'] },
      { id: 'calculus', title: 'Why limits matter in calculus', paragraphs: ['A derivative is a limit of difference quotients, while a definite integral is a limit of sums. Limits provide the common foundation for both ideas.'] },
    ],
  }),
  guide({
    slug: 'limit-laws', trSlug: 'limit-alma-kurallari', category: 'Limits & Continuity', symbol: 'lim', formula: 'sum · product', readingTime: 10,
    title: 'Limit Laws and Step-by-Step Examples',
    description: 'Use sum, product, quotient, and power laws to evaluate limits and decide what to do when substitution is inconclusive.',
    summary: 'Try direct substitution first; if it produces an indeterminate form, simplify the expression before evaluating the limit.',
    sections: [
      { id: 'laws', title: 'Sum, product, and constant laws', paragraphs: ['When the component limits exist, limits preserve addition, subtraction, multiplication, and constant multiples.'], formulas: ['lim(f±g)=lim f ± lim g', 'lim(kf)=k·lim f', 'lim(fg)=(lim f)(lim g)'] },
      { id: 'quotient', title: 'Quotient and power laws', paragraphs: ['A quotient can be split into separate limits provided the denominator limit is not zero. Powers and roots also pass through limits when their domain conditions are satisfied.'], formulas: ['lim(f/g)=lim f / lim g'] },
      { id: 'substitution', title: 'When direct substitution works', paragraphs: ['Polynomials are continuous everywhere, and rational functions are continuous wherever their denominator is nonzero. At such points, substitute the target value directly.'], formulas: ['lim(x→3)(2x²−x+1)=16'] },
      { id: 'strategy', title: 'When substitution gives 0/0', paragraphs: ['The form 0/0 is not an answer. Factor, rationalize with a conjugate, combine fractions, or use another transformation that reveals the nearby behavior.'] },
    ],
  }),
  guide({
    slug: 'one-sided-limits', trSlug: 'sagdan-ve-soldan-limit', category: 'Limits & Continuity', symbol: 'a⁻ a⁺', formula: 'L⁻ = L⁺',
    title: 'One-Sided Limits: Limits from the Left and Right',
    description: 'Evaluate left-hand and right-hand limits from graphs and piecewise functions, and determine when a two-sided limit exists.',
    summary: 'A two-sided limit exists only when the left-hand and right-hand limits both exist and are equal.',
    sections: [
      { id: 'notation', title: 'One-sided limit notation', paragraphs: ['Approaching a through values smaller than a is a left-hand limit; approaching through larger values is a right-hand limit.'], formulas: ['lim(x→a⁻)f(x)', 'lim(x→a⁺)f(x)'] },
      { id: 'condition', title: 'Condition for a two-sided limit', paragraphs: ['If either one-sided limit fails to exist or the two values differ, the two-sided limit does not exist.'], formulas: ['lim(x→a)f(x)=L ⇔ lim(x→a⁻)f(x)=lim(x→a⁺)f(x)=L'] },
      { id: 'piecewise', title: 'Piecewise-function example', paragraphs: ['Let f(x)=x+1 for x<2 and f(x)=5−x for x≥2. Both expressions approach 3 at x=2, so the two-sided limit is 3.'], formulas: ['left limit = 3', 'right limit = 3'] },
      { id: 'endpoints', title: 'Endpoints and jump discontinuities', paragraphs: ['At a domain endpoint only the available one-sided limit is relevant. When finite one-sided limits differ, the graph has a jump discontinuity.'] },
    ],
  }),
  guide({
    slug: 'indeterminate-forms-in-limits', trSlug: 'limitte-belirsizlikler', category: 'Limits & Continuity', symbol: '0/0', formula: 'simplify', readingTime: 11,
    title: 'Indeterminate Forms in Limits and How to Resolve Them',
    description: 'Resolve 0/0, infinity over infinity, and related indeterminate forms by factoring, rationalizing, comparing dominant terms, and using L’Hôpital’s rule.',
    summary: 'An indeterminate form is a signal to transform the expression; it does not determine the value of the limit by itself.',
    sections: [
      { id: 'forms', title: 'Common indeterminate forms', paragraphs: ['Different expressions with the same apparent form can have different limits, so these symbols cannot be treated as numerical answers.'], formulas: ['0/0, ∞/∞, 0·∞, ∞−∞, 1^∞, 0⁰, ∞⁰'] },
      { id: 'factoring', title: 'Factoring and cancellation', paragraphs: ['For polynomial quotients, factoring often exposes a removable common factor.'], formulas: ['lim(x→3)(x²−9)/(x−3)=lim(x→3)(x+3)=6'] },
      { id: 'rationalizing', title: 'Rationalizing and dominant terms', paragraphs: ['Use a conjugate for differences involving square roots. At infinity, divide every term by the highest relevant power to compare dominant terms.'], formulas: ['(√x−2)(√x+2)=x−4'] },
      { id: 'lhopital', title: 'When to use L’Hôpital’s rule', paragraphs: ['Under the required differentiability conditions, a 0/0 or ∞/∞ quotient may be evaluated through the quotient of derivatives. Check for an easier algebraic method first.'], formulas: ['lim f/g = lim f′/g′  (when the conditions hold)'] },
    ],
  }),
  guide({
    slug: 'what-is-continuity', trSlug: 'sureklilik-nedir', category: 'Limits & Continuity', symbol: 'f(a)', formula: 'limit = value', readingTime: 10,
    title: 'What Is Continuity? Three Conditions and Examples',
    description: 'Learn the three conditions for continuity at a point, continuity on intervals, and the role of the Intermediate Value Theorem.',
    summary: 'A function is continuous at a when f(a) is defined, the limit at a exists, and that limit equals f(a).',
    sections: [
      { id: 'conditions', title: 'The three conditions for continuity', paragraphs: ['All three conditions must hold together. Having a function value or a limit alone is not sufficient.'], formulas: ['1) f(a) is defined', '2) lim(x→a)f(x) exists', '3) lim(x→a)f(x)=f(a)'] },
      { id: 'families', title: 'Standard continuous functions', paragraphs: ['Polynomials are continuous on all real numbers. Rational, radical, logarithmic, and trigonometric functions are continuous wherever they are defined.'] },
      { id: 'piecewise', title: 'Continuity of a piecewise function', paragraphs: ['At a joining point, set the left-hand limit, right-hand limit, and function value equal. This often determines an unknown coefficient.'] },
      { id: 'ivt', title: 'The Intermediate Value Theorem', paragraphs: ['If f is continuous on [a,b], it takes every value between f(a) and f(b). This result is commonly used to prove that an equation has a root in an interval.'] },
    ],
  }),
  guide({
    slug: 'types-of-discontinuity', trSlug: 'sureksizlik-turleri', category: 'Limits & Continuity', symbol: '○│', formula: 'hole · jump',
    title: 'Types of Discontinuity: Removable, Jump, and Infinite',
    description: 'Classify removable, jump, infinite, and oscillating discontinuities by comparing one-sided limits and function values.',
    summary: 'The type of discontinuity depends on whether the one-sided limits exist, agree, and remain finite.',
    sections: [
      { id: 'removable', title: 'Removable discontinuity', paragraphs: ['The two-sided limit is finite, but the function value is missing or different. Defining f(a) to equal the limit fills the hole.'] },
      { id: 'jump', title: 'Jump discontinuity', paragraphs: ['The one-sided limits are finite but unequal. Changing only the value at the point cannot remove the jump.'], formulas: ['lim(x→a⁻)f(x) ≠ lim(x→a⁺)f(x)'] },
      { id: 'infinite', title: 'Infinite discontinuity', paragraphs: ['If values grow without bound near a, the line x=a is typically a vertical asymptote.'], formulas: ['lim(x→a)f(x)=±∞'] },
      { id: 'classify', title: 'A reliable classification process', paragraphs: ['Find both one-sided limits first, then compare the two-sided limit with f(a). This sequence distinguishes a hole, a jump, an asymptote, and oscillation.'] },
    ],
  }),
  guide({
    slug: 'differentiability-and-continuity', trSlug: 'turevlenebilirlik-ve-sureklilik', category: 'Limits & Continuity', symbol: 'f′ ⇒ f', formula: 'not conversely',
    title: 'Differentiability and Continuity: What Is the Relationship?',
    description: 'Understand why differentiability implies continuity and why a continuous function can still fail to be differentiable.',
    summary: 'Differentiability at a point implies continuity there, but continuity does not guarantee differentiability.',
    sections: [
      { id: 'theorem', title: 'Differentiability implies continuity', paragraphs: ['A finite derivative controls the difference f(x)−f(a) as x approaches a, forcing that difference to approach zero.'], formulas: ['differentiable at a ⇒ continuous at a'] },
      { id: 'converse', title: 'Why the converse fails', paragraphs: ['A continuous graph can have a corner, cusp, or vertical tangent. In these cases the graph does not break, but it has no single finite tangent slope.'] },
      { id: 'absolute', title: 'The absolute-value example', paragraphs: ['The function |x| is continuous at zero, but its left-hand slope is −1 and its right-hand slope is 1.'], formulas: ['f′(0⁻)=−1', 'f′(0⁺)=1'] },
      { id: 'check', title: 'How to check a graph', paragraphs: ['Check continuity first. Then look for corners and cusps, and finally compare finite one-sided tangent slopes. A discontinuous function cannot be differentiable at that point.'] },
    ],
  }),
  guide({
    slug: 'trigonometric-functions', trSlug: 'trigonometrik-fonksiyonlar', category: 'Trigonometry', symbol: 'sin θ', formula: 'opposite/hypotenuse', readingTime: 11,
    title: 'Trigonometric Functions: Definitions, Graphs, and Examples',
    description: 'Learn sine, cosine, tangent, and the reciprocal trigonometric functions through right triangles, the unit circle, and graphs.',
    summary: 'Trigonometric functions map angles to ratios; the unit circle extends these definitions to all real angles.',
    sections: [
      { id: 'ratios', title: 'The six trigonometric functions', paragraphs: ['In a right triangle, sine is opposite over hypotenuse, cosine is adjacent over hypotenuse, and tangent is opposite over adjacent. The other three functions are reciprocals.'], formulas: ['sinθ=opposite/hypotenuse', 'cosθ=adjacent/hypotenuse', 'tanθ=sinθ/cosθ'] },
      { id: 'circle', title: 'Definitions on the unit circle', paragraphs: ['The point reached by an angle θ on the unit circle has coordinates (cosθ,sinθ). This definition includes negative angles and angles larger than 90 degrees.'], formulas: ['P(cosθ, sinθ)'] },
      { id: 'graphs', title: 'Sine and cosine graphs', paragraphs: ['Both functions have range [−1,1] and period 2π. In y=A sin(Bx+C)+D, A controls amplitude and B controls period.'], formulas: ['period=2π/|B|'] },
      { id: 'calculus', title: 'Connection to calculus', paragraphs: ['Trigonometric limits, derivatives, and integrals use radian measure. The unit circle and radians are therefore essential prerequisites for calculus.'] },
    ],
  }),
  guide({
    slug: 'unit-circle-and-radians', trSlug: 'birim-cember-ve-radyan', category: 'Trigonometry', symbol: '2π', formula: 's=rθ', readingTime: 10,
    title: 'The Unit Circle and Radian Measure',
    description: 'Convert degrees and radians, find special-angle coordinates, and determine trigonometric signs by quadrant.',
    summary: 'A radian is the ratio of arc length to radius; on the unit circle, the angle equals its intercepted arc length.',
    sections: [
      { id: 'radian', title: 'What is a radian?', paragraphs: ['If an angle intercepts arc length s in a circle of radius r, its measure is θ=s/r radians. A full turn is 2π radians.'], formulas: ['θ=s/r', '360°=2π rad', '180°=π rad'] },
      { id: 'convert', title: 'Degree–radian conversion', paragraphs: ['Multiply degrees by π/180 to obtain radians, or radians by 180/π to obtain degrees.'], formulas: ['60°=π/3', '3π/4=135°'] },
      { id: 'coordinates', title: 'Special-angle coordinates', paragraphs: ['On the unit circle, cosine is the x-coordinate and sine is the y-coordinate. Symmetry generates values in all four quadrants from first-quadrant reference angles.'], formulas: ['π/4 → (√2/2, √2/2)'] },
      { id: 'calculus', title: 'Why calculus uses radians', paragraphs: ['The standard limits and derivative formulas for sine and cosine take their simplest form only when angles are measured in radians.'], formulas: ['lim(x→0) sinx/x=1', '(sin x)′=cos x'] },
    ],
  }),
  guide({
    slug: 'fundamental-trigonometric-identities', trSlug: 'temel-trigonometrik-ozdeslikler', category: 'Trigonometry', symbol: 'sin²+cos²', formula: '=1', readingTime: 10,
    title: 'Fundamental Trigonometric Identities and Examples',
    description: 'Use Pythagorean, angle-sum, double-angle, and related identities to simplify expressions and prepare for calculus.',
    summary: 'Identities hold for every value in their domain; rewriting an expression in one function family often reveals the solution.',
    sections: [
      { id: 'pythagorean', title: 'Pythagorean identities', paragraphs: ['Substituting the unit-circle coordinates into x²+y²=1 gives the primary identity. Dividing it produces two related identities.'], formulas: ['sin²x+cos²x=1', '1+tan²x=sec²x', '1+cot²x=csc²x'] },
      { id: 'sum', title: 'Angle-sum and difference identities', paragraphs: ['These identities express the trigonometric value of a combined angle in terms of its components.'], formulas: ['sin(a±b)=sin a cos b ± cos a sin b', 'cos(a±b)=cos a cos b ∓ sin a sin b'] },
      { id: 'double', title: 'Double-angle identities', paragraphs: ['Set the two angles equal in the sum formulas, then use the Pythagorean identity to obtain equivalent cosine forms.'], formulas: ['sin2x=2sinx cosx', 'cos2x=cos²x−sin²x=1−2sin²x'] },
      { id: 'strategy', title: 'A simplification strategy', paragraphs: ['Begin with the more complicated side, rewrite tangent and secant using sine and cosine when useful, combine fractions, and transform only one side of an identity at a time.'] },
    ],
  }),
  guide({
    slug: 'exponential-and-logarithmic-functions', trSlug: 'ustel-ve-logaritmik-fonksiyonlar', category: 'Functions', symbol: 'eˣ ln x', formula: 'inverse functions', readingTime: 11,
    title: 'Exponential and Logarithmic Functions: Core Properties',
    description: 'Learn exponential growth, logarithms, natural logarithms, graphs, domain restrictions, and basic equation-solving techniques.',
    summary: 'The functions aˣ and logₐx are inverses: exponentials model multiplicative change, while logarithms identify the required exponent.',
    sections: [
      { id: 'exponential', title: 'Properties of exponential functions', paragraphs: ['For f(x)=aˣ, require a>0 and a≠1. The domain is all real numbers and the range is positive. The function increases for a>1 and decreases for 0<a<1.'], formulas: ['a⁰=1', 'a^(x+y)=aˣaʸ'] },
      { id: 'logarithm', title: 'What is a logarithm?', paragraphs: ['The value logₐx answers: to what power must a be raised to obtain x? This inverse relationship requires x>0.'], formulas: ['logₐx=y ⇔ aʸ=x'] },
      { id: 'laws', title: 'Logarithm laws', paragraphs: ['Products become sums, quotients become differences, and powers become coefficients. Every logarithm argument must remain positive.'], formulas: ['logₐ(xy)=logₐx+logₐy', 'logₐ(x/y)=logₐx−logₐy', 'logₐ(xʳ)=r logₐx'] },
      { id: 'equations', title: 'Solving exponential equations', paragraphs: ['Match bases when possible. Otherwise take logarithms on both sides, solve, and check all domain restrictions.'], formulas: ['2^(x+1)=8=2³ ⇒ x=2'] },
    ],
  }),
  guide({
    slug: 'functions-and-graphs', trSlug: 'fonksiyonlar-ve-grafikler', category: 'Functions', symbol: 'f(x)', formula: 'x ↦ y', readingTime: 12,
    title: 'Functions and Graphs: Preparation for University Calculus',
    description: 'Review functions, domains and ranges, graph transformations, composition, and inverse functions before studying calculus.',
    summary: 'A function assigns each valid input exactly one output; domains, graphs, and transformations form the common language of calculus.',
    sections: [
      { id: 'definition', title: 'What is a function?', paragraphs: ['A relation is a function when every input in its domain has exactly one output. Different inputs may still share the same output.'], formulas: ['f:A→B', 'y=f(x)'] },
      { id: 'domain', title: 'Domain and range', paragraphs: ['The domain contains allowable inputs; the range contains outputs actually produced. Denominators cannot be zero, even-root radicands cannot be negative, and logarithm arguments must be positive.'] },
      { id: 'transformations', title: 'Graph transformations', paragraphs: ['Adding outside f shifts vertically, changing the input shifts horizontally, and multiplying by −1 reflects a graph.'], formulas: ['y=f(x−h)+k ⇒ h units right, k units up'] },
      { id: 'composition', title: 'Composition and inverse functions', paragraphs: ['A composition feeds one function’s output into another. An inverse exchanges input and output and exists on an interval where the original function is one-to-one.'], formulas: ['(f∘g)(x)=f(g(x))', 'f⁻¹(f(x))=x'] },
    ],
  }),
];
