const article = (data) => ({
  publishedAt: '2026-08-27', level: 'Üniversiteye hazırlık', ...data,
  keywords: data.keywords || [data.shortTitle.toLocaleLowerCase('tr-TR'), 'matematik konu anlatımı', 'çözümlü örnekler'],
});

export const foundationArticles = [
  article({
    slug: 'limit-nedir', shortTitle: 'Limit Nedir?', category: 'Limit ve Süreklilik', symbol: 'lim', formula: 'x → a', readingTime: 10,
    title: 'Limit Nedir? Sezgisel Anlamı ve Çözümlü Örnekler',
    description: 'Limitin bir fonksiyonun belirli bir noktaya yaklaşırken nasıl davrandığını anlattığını grafik, tablo ve çözümlü örneklerle öğrenin.',
    summary: 'Limit, x bir değere yaklaşırken f(x)’in yaklaştığı değeri inceler; fonksiyonun o noktadaki değeriyle aynı olmak zorunda değildir.',
    intro: ['Limit, türev ve integralin üzerine kurulduğu temel fikirdir. Bir noktaya doğrudan ulaşmaktan çok, o noktaya istenildiği kadar yaklaşırken fonksiyonun davranışını inceler.', 'Grafik, değer tablosu ve cebirsel işlemler aynı limitin farklı görünümleridir.'],
    sections: [
      ['anlam', 'Limit Ne Anlama Gelir?', ['x değerleri a’ya hem soldan hem sağdan yaklaşırken f(x) değerleri aynı L sayısına yaklaşıyorsa fonksiyonun a noktasındaki limiti L’dir.'], ['lim(x→a) f(x) = L']],
      ['deger', 'Limit ile Fonksiyon Değeri Farkı', ['f(a) tanımsız olsa veya L’den farklı olsa bile limit var olabilir. Limit komşu noktalardaki davranışı, f(a) ise tek bir noktadaki değeri anlatır.'], []],
      ['grafik', 'Grafik ve Tablodan Limit Okuma', ['Grafikte x=a doğrusuna iki yönden yaklaşın. Y değerleri aynı yüksekliğe gidiyorsa iki taraflı limit vardır; farklı değerlere gidiyorsa yoktur.'], []],
      ['ornek', 'Çözümlü Örnek', ['İfade x=2’de 0/0 verse de payı çarpanlara ayırıp ortak çarpanı sadeleştirebiliriz.'], ['lim(x→2) (x²−4)/(x−2)', '= lim(x→2) (x+2) = 4']],
      ['baglanti', 'Limit Neden Önemlidir?', ['Türev, fark oranının limiti; belirli integral ise toplamların limitidir. Bu nedenle limit fikri anlaşılmadan kalkülüs kuralları birbirinden kopuk görünür.'], []],
    ], related: { slug: 'limit-alma-kurallari', title: 'Limit Alma Kuralları', text: 'Limitleri cebirsel olarak hesaplamaya geçin' },
  }),
  article({
    slug: 'limit-alma-kurallari', shortTitle: 'Limit Alma Kuralları', category: 'Limit ve Süreklilik', symbol: 'lim', formula: 'toplam · bölüm', readingTime: 11,
    title: 'Limit Alma Kuralları ve Çözümlü Örnekler',
    description: 'Toplam, çarpım, bölüm ve kuvvet kurallarıyla limit hesaplamayı; belirsizlik oluştuğunda hangi yöntemi seçmeniz gerektiğini öğrenin.',
    summary: 'Önce doğrudan yerine koymayı deneyin; belirli bir değer çıkarsa bitirin, belirsizlik çıkarsa ifadeyi sadeleştirecek yöntemi seçin.',
    intro: ['Limit kuralları, karmaşık bir fonksiyonun limitini daha küçük parçaların limitlerinden hesaplamayı sağlar.', 'Kuralların uygulanabilmesi için ilgili limitlerin varlığı ve bölümde paydanın limitinin sıfır olmaması gerekir.'],
    sections: [
      ['temel', 'Temel Limit Kuralları', ['Sabit, toplam, fark ve sabit katsayı kuralları limit işlemini terimlere ayırır.'], ['lim(f±g)=lim f ± lim g', 'lim(kf)=k·lim f', 'lim(fg)=(lim f)(lim g)']],
      ['bolum', 'Bölüm ve Kuvvet Kuralları', ['Paydanın limiti sıfır değilse pay ve paydanın limitleri ayrı alınabilir. Uygun tanım koşullarında kuvvet ve kök işlemleri de limitin dışına taşınabilir.'], ['lim(f/g)=lim f / lim g']],
      ['yerine', 'Doğrudan Yerine Koyma', ['Polinomlarda ve paydası sıfır olmayan rasyonel fonksiyonlarda x yerine yaklaşma değeri yazılır.'], ['lim(x→3) (2x²−x+1) = 16']],
      ['belirsizlik', 'Belirsizlik Çıkarsa Ne Yapılır?', ['0/0 bir sonuç değil, ifadenin yeniden düzenlenmesi gerektiğini söyleyen bir işarettir. Çarpanlara ayırma, eşlenikle çarpma veya ortak payda kullanılabilir.'], []],
      ['kontrol', 'Çözüm Kontrol Listesi', ['Yaklaşma yönünü, tanım kümesini, sadeleştirilen ifadenin yalnızca komşulukta eşdeğer olduğunu ve son değerin iki taraftan aynı geldiğini kontrol edin.'], []],
    ], related: { slug: 'sagdan-ve-soldan-limit', title: 'Sağdan ve Soldan Limit', text: 'İki taraflı limitin varlık koşulunu öğrenin' },
  }),
  article({
    slug: 'sagdan-ve-soldan-limit', shortTitle: 'Sağdan ve Soldan Limit', category: 'Limit ve Süreklilik', symbol: 'a⁻ a⁺', formula: 'L⁻ = L⁺', readingTime: 9,
    title: 'Sağdan ve Soldan Limit Nasıl Bulunur?', description: 'Tek taraflı limitleri grafik ve parçalı fonksiyonlarla hesaplamayı, iki taraflı limitin ne zaman var olduğunu öğrenin.',
    summary: 'İki taraflı limit ancak sağ ve sol limitlerin ikisi de var ve birbirine eşitse vardır.',
    intro: ['Bir noktaya küçük değerlerden yaklaşmak soldan, büyük değerlerden yaklaşmak sağdan yaklaşmaktır.', 'Parçalı fonksiyonlarda, sıçramalı grafiklerde ve tanım kümesinin uçlarında bu ayrım zorunludur.'],
    sections: [
      ['tanim', 'Tek Taraflı Limit Gösterimi', ['x<a değerleriyle yaklaşmak a⁻, x>a değerleriyle yaklaşmak a⁺ sembolüyle gösterilir.'], ['lim(x→a⁻)f(x)', 'lim(x→a⁺)f(x)']],
      ['kosul', 'İki Taraflı Limitin Varlık Koşulu', ['Sağ ve sol limitlerden biri yoksa veya ikisi farklıysa iki taraflı limit yoktur.'], ['lim(x→a)f(x)=L ⇔ lim(x→a⁻)f(x)=lim(x→a⁺)f(x)=L']],
      ['parcali', 'Parçalı Fonksiyon Örneği', ['f(x)=x+1 (x<2) ve f(x)=5−x (x≥2) olsun. Her parçada x=2’ye yaklaşılır.'], ['Sol limit = 3', 'Sağ limit = 3', 'Bu nedenle limit = 3']],
      ['sicrama', 'Sıçrama Süreksizliği', ['Tek taraflı limitler sonlu fakat farklıysa grafik bir değerden diğerine sıçrar. Fonksiyonun noktadaki değerini değiştirmek iki taraflı limiti oluşturmaz.'], []],
      ['uc', 'Tanım Aralığının Uç Noktası', ['Fonksiyon yalnızca bir tarafta tanımlıysa o uç noktada ilgili tek taraflı limit incelenir. Örneğin √x için x→0⁺ anlamlıdır.'], []],
    ], related: { slug: 'limitte-belirsizlikler', title: 'Limitte Belirsizlikler', text: '0/0 ve diğer belirsiz biçimleri çözün' },
  }),
  article({
    slug: 'limitte-belirsizlikler', shortTitle: 'Limitte Belirsizlikler', category: 'Limit ve Süreklilik', symbol: '0/0', formula: 'sadeleştir', readingTime: 12,
    title: 'Limitte Belirsizlikler ve Çözüm Yöntemleri', description: '0/0 ve ∞/∞ başta olmak üzere limit belirsizliklerini çarpanlara ayırma, eşlenik ve L’Hôpital yöntemiyle çözün.',
    summary: 'Belirsiz biçim nihai cevap değildir; ifadenin baskın davranışını ortaya çıkaracak cebirsel veya analitik dönüşüm gerekir.',
    intro: ['Doğrudan yerine koyma bazen 0/0 veya ∞/∞ gibi sonuca karar vermeyen biçimler üretir.', 'Aynı belirsiz biçim farklı limit değerlerine gidebildiği için yalnızca sembole bakarak sonuç söylenemez.'],
    sections: [
      ['bicimler', 'Yaygın Belirsiz Biçimler', ['0/0 ve ∞/∞ kesirlerde; 0·∞ çarpımlarda; ∞−∞ farklarda; 1^∞, 0⁰ ve ∞⁰ üs ifadelerinde görülür.'], ['0/0, ∞/∞, 0·∞, ∞−∞, 1^∞, 0⁰, ∞⁰']],
      ['carpan', 'Çarpanlara Ayırma', ['Polinomlarda ortak çarpan sadeleştirildiğinde kaldırılabilir süreksizlik görünür hâle gelir.'], ['lim(x→3) (x²−9)/(x−3)=lim(x→3)(x+3)=6']],
      ['eslenik', 'Eşlenikle Çarpma', ['Köklü ifadelerde eşlenik, pay veya paydadaki farkı çarpanlara dönüştürür.'], ['(√x−2)(√x+2)=x−4']],
      ['sonsuz', 'Sonsuzda Baskın Terim', ['Rasyonel fonksiyonlarda pay ve paydanın en yüksek dereceli terimleri davranışı belirler. Her terimi en yüksek x kuvvetine bölmek yöntemi görünür kılar.'], []],
      ['lhopital', 'L’Hôpital Kuralı Ne Zaman Kullanılır?', ['Uygun türevlenebilirlik koşullarında 0/0 veya ∞/∞ biçimlerinde pay ve paydanın türevlerinin limiti incelenebilir. Önce daha basit cebirsel yöntemi kontrol edin.'], ['lim f/g = lim f′/g′  (koşullar sağlanıyorsa)']],
    ], related: { slug: 'sureklilik-nedir', title: 'Süreklilik Nedir?', text: 'Limit ile fonksiyon değerini birleştirin' },
  }),
  article({
    slug: 'sureklilik-nedir', shortTitle: 'Süreklilik Nedir?', category: 'Limit ve Süreklilik', symbol: 'f(a)', formula: 'lim = değer', readingTime: 10,
    title: 'Süreklilik Nedir? Üç Şart ve Çözümlü Örnekler', description: 'Bir fonksiyonun bir noktada ve aralıkta sürekli olma koşullarını limit yardımıyla öğrenin.',
    summary: 'f fonksiyonunun a’da sürekli olması için f(a) tanımlı, lim(x→a)f(x) var ve bu iki değer eşit olmalıdır.',
    intro: ['Sezgisel olarak sürekli bir grafik, kalemi kaldırmadan çizilebilir. Matematiksel tanım ise bu fikri üç kesin koşulla ifade eder.', 'Süreklilik, limitten türeve geçişteki temel köprüdür ve ara değer teoremi gibi önemli sonuçları mümkün kılar.'],
    sections: [
      ['uc-sart', 'Bir Noktada Sürekliliğin Üç Şartı', ['Üç koşul birlikte sağlanmalıdır; yalnızca limitin varlığı veya fonksiyonun tanımlı olması yeterli değildir.'], ['1) f(a) tanımlı', '2) lim(x→a)f(x) var', '3) lim(x→a)f(x)=f(a)']],
      ['fonksiyonlar', 'Temel Sürekli Fonksiyonlar', ['Polinomlar her gerçek sayıda; rasyonel fonksiyonlar paydanın sıfır olmadığı yerlerde; kök, logaritma ve trigonometrik fonksiyonlar kendi tanım kümelerinde süreklidir.'], []],
      ['parcali', 'Parçalı Fonksiyonda Süreklilik', ['Birleşme noktasında sol limit, sağ limit ve fonksiyon değeri eşitlenir. Bu eşitlik bilinmeyen katsayıyı bulmak için kullanılabilir.'], []],
      ['aralik', 'Bir Aralıkta Süreklilik', ['Açık aralıkta her noktada iki taraflı süreklilik gerekir. Kapalı [a,b] aralığında ayrıca a’da sağdan, b’de soldan süreklilik aranır.'], []],
      ['ara-deger', 'Ara Değer Teoremi', ['[a,b] üzerinde sürekli bir fonksiyon f(a) ile f(b) arasındaki her değeri en az bir kez alır. Bu sonuç köklerin varlığını göstermede kullanılır.'], []],
    ], related: { slug: 'sureksizlik-turleri', title: 'Süreksizlik Türleri', text: 'Grafikteki kopmaların türlerini ayırt edin' },
  }),
  article({
    slug: 'sureksizlik-turleri', shortTitle: 'Süreksizlik Türleri', category: 'Limit ve Süreklilik', symbol: '○│', formula: 'giderilebilir · sıçrama', readingTime: 9,
    title: 'Süreksizlik Türleri: Giderilebilir, Sıçrama ve Sonsuz', description: 'Fonksiyon grafiklerindeki giderilebilir, sıçrama ve sonsuz süreksizlikleri limitlerle sınıflandırın.',
    summary: 'Süreksizliğin türü sağ-sol limitlerin varlığına, eşitliğine ve sonlu olup olmamasına göre belirlenir.',
    intro: ['Bir fonksiyonun sürekli olmaması farklı nedenlerden kaynaklanabilir. Bu nedenleri ayırmak, sorunun hangi değişiklikle düzeltilebileceğini gösterir.', 'Grafikte delik, sıçrama veya düşey asimptot görmek limit davranışının görsel karşılığıdır.'],
    sections: [
      ['giderilebilir', 'Giderilebilir Süreksizlik', ['İki taraflı limit sonlu ve var, fakat fonksiyon değeri yok veya limite eşit değilse grafik üzerinde bir delik oluşur. f(a) limit değerine eşit tanımlanarak süreklilik sağlanabilir.'], []],
      ['sicrama', 'Sıçrama Süreksizliği', ['Sağ ve sol limitler sonlu fakat farklıdır. Noktadaki tek bir değeri değiştirmek bu kopmayı gideremez.'], ['lim(x→a⁻)f(x) ≠ lim(x→a⁺)f(x)']],
      ['sonsuz', 'Sonsuz Süreksizlik', ['Fonksiyon a’ya yaklaşırken sınırsız büyüyor veya küçülüyorsa x=a çoğunlukla düşey asimptottur.'], ['lim(x→a)f(x)=±∞']],
      ['salinim', 'Salınımlı Davranış', ['sin(1/x) gibi fonksiyonlar noktaya yaklaşırken tek bir değere yerleşmeden sürekli salınabilir; bu durumda limit yoktur.'], []],
      ['siniflandir', 'Süreksizlik Nasıl Sınıflandırılır?', ['Önce sağ ve sol limitleri bulun, sonra iki taraflı limiti ve f(a)’yı karşılaştırın. Bu sıra görsel tahmin yerine kesin sınıflandırma sağlar.'], []],
    ], related: { slug: 'turevlenebilirlik-ve-sureklilik', title: 'Türevlenebilirlik ve Süreklilik', text: 'İki kavram arasındaki mantıksal ilişkiyi öğrenin' },
  }),
  article({
    slug: 'turevlenebilirlik-ve-sureklilik', shortTitle: 'Türevlenebilirlik ve Süreklilik', category: 'Limit ve Süreklilik', symbol: 'f′ ⇒ f', formula: 'tersi şart değil', readingTime: 9,
    title: 'Türevlenebilirlik ve Süreklilik Arasındaki İlişki', description: 'Türevlenebilirliğin neden süreklilik gerektirdiğini ve sürekli olup türevlenemeyen fonksiyonları örneklerle öğrenin.',
    summary: 'Bir fonksiyon bir noktada türevlenebilirse orada süreklidir; fakat sürekli olması türevlenebilir olduğunu garanti etmez.',
    intro: ['Türev, grafiğin bir noktadaki tek ve sonlu teğet eğimini arar. Böyle bir eğimin varlığı grafiğin o noktada kopmamasını gerektirir.', 'Mantıksal ilişkinin yönü sık karıştırıldığı için karşı örnekleri bilmek önemlidir.'],
    sections: [
      ['teorem', 'Türevlenebilirlik Sürekliliği Gerektirir', ['f′(a) sonlu olarak varsa fark oranı üzerinden f(x)−f(a) farkının sıfıra yaklaştığı ve dolayısıyla f’nin a’da sürekli olduğu gösterilebilir.'], ['a’da türevlenebilir ⇒ a’da sürekli']],
      ['tersi', 'Süreklilik Neden Yetmez?', ['Sürekli bir grafikte köşe, sivri uç veya düşey teğet bulunabilir. Bu noktalarda sağ ve sol eğimler uyuşmadığı ya da sonlu olmadığı için türev yoktur.'], []],
      ['mutlak', 'Mutlak Değer Örneği', ['f(x)=|x| fonksiyonu x=0’da süreklidir; ancak soldan eğim −1, sağdan eğim 1 olduğu için türevlenemez.'], ['f′(0⁻)=−1', 'f′(0⁺)=1']],
      ['kopuk', 'Süreksiz Fonksiyon Türevlenebilir mi?', ['Bir fonksiyon noktada süreksizse o noktada türevlenemez. Bu bilgi, türev hesabından önce hızlı bir eleme sağlar.'], []],
      ['kontrol', 'Grafikten Türevlenebilirlik Kontrolü', ['Önce sürekliliği, sonra köşe veya sivri uç bulunup bulunmadığını, son olarak sağ-sol teğet eğimlerinin eşit ve sonlu olup olmadığını inceleyin.'], []],
    ], related: { slug: 'turev-nedir', title: 'Türev Nedir?', text: 'Limit tanımından türeve geçin' },
  }),
  article({
    slug: 'trigonometrik-fonksiyonlar', shortTitle: 'Trigonometrik Fonksiyonlar', category: 'Trigonometri', symbol: 'sin θ', formula: 'karşı/hipotenüs', readingTime: 12,
    title: 'Trigonometrik Fonksiyonlar: Temel Kavramlar ve Grafikler', description: 'Sinüs, kosinüs, tanjant ve diğer trigonometrik fonksiyonları dik üçgen, birim çember ve grafikler üzerinden öğrenin.',
    summary: 'Trigonometrik fonksiyonlar bir açıyı oranla eşler; birim çember bu tanımları tüm gerçek açılara genişletir.',
    intro: ['Trigonometri yalnızca üçgen çözmek için değil, periyodik hareketleri ve kalkülüsteki özel fonksiyonları anlamak için kullanılır.', 'Dik üçgen tanımı başlangıçtır; üniversite düzeyinde esas bütünlük birim çember ve radyanla kurulur.'],
    sections: [
      ['oranlar', 'Altı Trigonometrik Oran', ['Dik üçgende sinüs karşı/hipotenüs, kosinüs komşu/hipotenüs, tanjant karşı/komşudur. Diğer üç fonksiyon bunların çarpmaya göre tersidir.'], ['sinθ=karşı/hipotenüs', 'cosθ=komşu/hipotenüs', 'tanθ=sinθ/cosθ']],
      ['cember', 'Birim Çember Tanımı', ['Birim çemberde θ açısına karşılık gelen noktanın koordinatları (cosθ,sinθ)’dir. Bu tanım negatif ve 90 dereceden büyük açılara da uygulanır.'], ['P(cosθ, sinθ)']],
      ['grafikler', 'Sinüs ve Kosinüs Grafikleri', ['İki fonksiyonun periyodu 2π, değer aralığı [−1,1]’dir. Genlik ve periyot dönüşümleri dalganın yüksekliğini ve sıklığını değiştirir.'], ['y=A sin(Bx+C)+D', 'periyot=2π/|B|']],
      ['tanjant', 'Tanjant Grafiği', ['tan x=sin x/cos x olduğundan cos x=0 noktalarında tanımsızdır ve düşey asimptotları vardır. Temel periyodu π’dir.'], []],
      ['kalkulus', 'Kalkülüsle Bağlantı', ['Trigonometrik limitler, türevler ve integraller radyan ölçüsüne dayanır. Bu nedenle sonraki adımda birim çember ve radyan birlikte pekiştirilmelidir.'], []],
    ], related: { slug: 'birim-cember-ve-radyan', title: 'Birim Çember ve Radyan', text: 'Açıları kalkülüse uygun biçimde yorumlayın' },
  }),
  article({
    slug: 'birim-cember-ve-radyan', shortTitle: 'Birim Çember ve Radyan', category: 'Trigonometri', symbol: '2π', formula: 's=rθ', readingTime: 10,
    title: 'Birim Çember ve Radyan Ölçüsü', description: 'Derece-radyan dönüşümünü, özel açıların birim çemberdeki koordinatlarını ve işaret bölgelerini öğrenin.',
    summary: 'Radyan, yay uzunluğunun yarıçapa oranıdır; birim çemberde açı doğrudan yay uzunluğuna eşittir.',
    intro: ['Radyan açı ölçüsü, trigonometrik fonksiyonların limit ve türev formüllerini doğal hâle getirir.', 'Birim çember özel açı değerlerini ezberden çok koordinat ve simetriyle üretmenizi sağlar.'],
    sections: [
      ['tanim', 'Radyan Nedir?', ['Merkez açının gördüğü yay uzunluğu s ve yarıçap r ise açı θ=s/r radyandır. Tam çemberin çevresi 2πr olduğu için tam dönüş 2π radyandır.'], ['θ=s/r', '360°=2π rad', '180°=π rad']],
      ['donusum', 'Derece–Radyan Dönüşümü', ['Dereceden radyana π/180 ile, radyandan dereceye 180/π ile çarpılarak geçilir.'], ['60°=π/3', '3π/4=135°']],
      ['koordinat', 'Özel Açı Koordinatları', ['Birim çemberde x koordinatı kosinüs, y koordinatı sinüstür. 0, π/6, π/4, π/3 ve π/2 açıları ilk bölgedeki temel değerleri verir.'], ['π/4 → (√2/2, √2/2)']],
      ['isaret', 'Bölgelere Göre İşaretler', ['Birinci bölgede sinüs ve kosinüs pozitif; ikinci bölgede yalnız sinüs; üçüncüde yalnız tanjant; dördüncüde yalnız kosinüs pozitiftir.'], []],
      ['neden', 'Kalkülüste Neden Radyan Kullanılır?', ['lim(x→0) sinx/x=1 ve (sin x)′=cos x formülleri x radyan cinsindeyken bu sade biçimdedir. Derece kullanılırsa ek sabit katsayı oluşur.'], []],
    ], related: { slug: 'temel-trigonometrik-ozdeslikler', title: 'Temel Trigonometrik Özdeşlikler', text: 'Fonksiyonlar arasındaki eşitlikleri kullanın' },
  }),
  article({
    slug: 'temel-trigonometrik-ozdeslikler', shortTitle: 'Trigonometrik Özdeşlikler', category: 'Trigonometri', symbol: 'sin²+cos²', formula: '=1', readingTime: 11,
    title: 'Temel Trigonometrik Özdeşlikler ve Uygulamaları', description: 'Pisagor, toplam-fark, iki kat açı ve yarım açı özdeşliklerini sadeleştirme ve denklem çözme örnekleriyle öğrenin.',
    summary: 'Özdeşlikler tanımlı oldukları tüm değerlerde doğrudur; ifadeyi aynı fonksiyon ailesine dönüştürmek çoğu soruyu sadeleştirir.',
    intro: ['Trigonometrik özdeşlikler farklı görünen ifadelerin aynı değeri taşıdığını gösterir.', 'Türev ve integral işlemlerinde uygun özdeşlik, doğrudan uygulanamayan bir ifadeyi bilinen forma dönüştürür.'],
    sections: [
      ['pisagor', 'Pisagor Özdeşlikleri', ['Birim çemberde x²+y²=1 eşitliğine cosθ ve sinθ yazılması temel özdeşliği verir. Bölme yoluyla iki ek özdeşlik elde edilir.'], ['sin²x+cos²x=1', '1+tan²x=sec²x', '1+cot²x=csc²x']],
      ['toplam', 'Toplam ve Fark Formülleri', ['İki açının toplam veya farkının trigonometrik değeri tek tek açıların değerleriyle yazılabilir.'], ['sin(a±b)=sin a cos b ± cos a sin b', 'cos(a±b)=cos a cos b ∓ sin a sin b']],
      ['iki-kat', 'İki Kat Açı Formülleri', ['Toplam formüllerinde a=b seçilerek iki kat açı eşitlikleri elde edilir. Kosinüs formülü Pisagor özdeşliğiyle üç eşdeğer biçimde yazılabilir.'], ['sin2x=2sinx cosx', 'cos2x=cos²x−sin²x=1−2sin²x=2cos²x−1']],
      ['ornek', 'Sadeleştirme Örneği', ['(1−cos²x)/sinx ifadesinde 1−cos²x=sin²x kullanılır. sinx≠0 koşuluyla ifade sinx’e sadeleşir.'], ['(1−cos²x)/sinx = sinx']],
      ['strateji', 'Özdeşlik Sorusu Stratejisi', ['Daha karmaşık taraftan başlayın, tanjant ve sekantı sinüs-kosinüs cinsinden yazmayı deneyin, payda eşitleyin ve yalnızca bir tarafı dönüştürün.'], []],
    ], related: { slug: 'ustel-ve-logaritmik-fonksiyonlar', title: 'Üstel ve Logaritmik Fonksiyonlar', text: 'Kalkülüsün diğer temel fonksiyon ailesine geçin' },
  }),
  article({
    slug: 'ustel-ve-logaritmik-fonksiyonlar', shortTitle: 'Üstel ve Logaritmik Fonksiyonlar', category: 'Fonksiyonlar', symbol: 'eˣ ln x', formula: 'ters fonksiyon', readingTime: 12,
    title: 'Üstel ve Logaritmik Fonksiyonlar: Temel Özellikler', description: 'Üstel büyüme, logaritma, doğal logaritma, grafikler ve temel denklem çözme yöntemlerini öğrenin.',
    summary: 'aˣ ve logₐx birbirinin tersidir; üstel fonksiyon çarpımsal değişimi, logaritma ise gereken üssü ifade eder.',
    intro: ['Üstel fonksiyonlar sabit bir oranla büyüme ve azalmayı; logaritmalar bu sürecin tersini modeller.', 'Bileşik faizden nüfus modellerine, türev ve integrallerden diferansiyel denklemlere kadar geniş bir kullanım alanları vardır.'],
    sections: [
      ['ustel', 'Üstel Fonksiyonun Özellikleri', ['f(x)=aˣ için a>0 ve a≠1 olmalıdır. Tanım kümesi gerçek sayılar, değer kümesi pozitif gerçek sayılardır. a>1 ise artan, 0<a<1 ise azalandır.'], ['a⁰=1', 'a^(x+y)=aˣaʸ']],
      ['log', 'Logaritma Nedir?', ['logₐx, a’nın hangi kuvvetinin x olduğunu sorar. Bu tanım x>0 koşulunu ve üstel-logaritmik dönüşümü verir.'], ['logₐx=y ⇔ aʸ=x']],
      ['kurallar', 'Logaritma Kuralları', ['Çarpım toplama, bölüm çıkarma, kuvvet ise katsayıya dönüşür. Kurallar uygulanırken her logaritma argümanı pozitif olmalıdır.'], ['logₐ(xy)=logₐx+logₐy', 'logₐ(x/y)=logₐx−logₐy', 'logₐ(xʳ)=r logₐx']],
      ['dogal', 'e Sayısı ve Doğal Logaritma', ['e tabanı sürekli büyümenin doğal sabitidir. ln x=logₑx gösterimi kalkülüste özel öneme sahiptir çünkü eˣ’in türevi kendisidir.'], []],
      ['denklem', 'Üstel ve Logaritmik Denklem Çözme', ['Mümkünse tabanları eşitleyin. Eşitlenemiyorsa iki tarafın logaritmasını alın ve çözümün tanım koşullarını kontrol edin.'], ['2^(x+1)=8=2³ ⇒ x=2']],
    ], related: { slug: 'fonksiyonlar-ve-grafikler', title: 'Fonksiyonlar ve Grafikler', text: 'Temel fonksiyon dilini bütün olarak gözden geçirin' },
  }),
  article({
    slug: 'fonksiyonlar-ve-grafikler', shortTitle: 'Fonksiyonlar ve Grafikler', category: 'Fonksiyonlar', symbol: 'f(x)', formula: 'x ↦ y', readingTime: 13,
    title: 'Fonksiyonlar ve Grafikler: Üniversite Matematiğine Hazırlık', description: 'Fonksiyon, tanım ve değer kümesi, grafik dönüşümleri, bileşke ve ters fonksiyon kavramlarını bütünlüklü biçimde öğrenin.',
    summary: 'Fonksiyon her geçerli girdiyi tek bir çıktıyla eşler; tanım kümesi, grafik ve dönüşümler sonraki tüm kalkülüs konularının ortak dilidir.',
    intro: ['Limit, türev ve integral bir fonksiyonun davranışını inceler. Bu nedenle kalkülüse başlamadan önce fonksiyon dilinin sağlam olması gerekir.', 'Cebirsel ifade, tablo ve grafik aynı fonksiyonu farklı biçimlerde temsil edebilir.'],
    sections: [
      ['tanim', 'Fonksiyon Nedir?', ['Bir bağıntının fonksiyon olması için tanım kümesindeki her elemanın değer kümesinde tam bir görüntüsü olmalıdır. Farklı girdiler aynı çıktıya gidebilir.'], ['f:A→B', 'y=f(x)']],
      ['kume', 'Tanım ve Değer Kümesi', ['Tanım kümesi izin verilen x değerleri, görüntü kümesi fonksiyonun gerçekten ürettiği y değerleridir. Payda sıfır olamaz, çift dereceli kökün içi negatif olamaz ve logaritmanın içi pozitif olmalıdır.'], []],
      ['grafik', 'Grafik Dönüşümleri', ['f(x)+k grafiği dikey, f(x−h) yatay öteler. −f(x) x eksenine, f(−x) y eksenine göre yansıtır.'], ['y=f(x−h)+k ⇒ h sağa, k yukarı']],
      ['bileske', 'Bileşke Fonksiyon', ['Bir fonksiyonun çıktısı diğerinin girdisi olduğunda bileşke oluşur. İç fonksiyonun çıktılarının dış fonksiyonun tanım kümesinde olması gerekir.'], ['(f∘g)(x)=f(g(x))']],
      ['ters', 'Ters Fonksiyon', ['Ters fonksiyon girdi ve çıktı rollerini değiştirir. Fonksiyonun tersinin olabilmesi için hedeflenen aralıkta bire bir olması gerekir; grafikler y=x doğrusuna göre simetriktir.'], ['f⁻¹(f(x))=x']],
    ], related: { slug: 'limit-nedir', title: 'Limit Nedir?', text: 'Fonksiyon davranışını bir noktaya yaklaşırken inceleyin' },
  }),
];

export const foundationArticleMap = Object.fromEntries(foundationArticles.map((item) => [item.slug, item]));
