import IntegralTopicArticle from '../../../components/public/IntegralTopicArticle';

const title = 'İntegral ile Alan Hesabı Nasıl Yapılır?';
const description = 'Eğri ile x ekseni ve iki eğri arasında kalan alanı integral kullanarak adım adım çözümlü örneklerle hesaplayın.';
export const metadata = {
  title, description, alternates: { canonical: '/makaleler/integral-ile-alan-hesabi' },
  keywords: ['integral ile alan hesabı', 'iki eğri arasındaki alan', 'belirli integral alan', 'AYT integral'],
  openGraph: { title, description, type: 'article', locale: 'tr_TR', siteName: 'MatAI', url: '/makaleler/integral-ile-alan-hesabi', images: [{ url: '/assets/og/integral-sorusu-nasil-cozulur.png', width: 1200, height: 630, alt: title }], publishedTime: '2026-08-12T00:00:00+03:00', modifiedTime: '2026-08-12T00:00:00+03:00', authors: ['MatAI'] },
  twitter: { card: 'summary_large_image', title, description, images: ['/assets/og/integral-sorusu-nasil-cozulur.png'] },
};
const article = { slug: 'integral-ile-alan-hesabi', title, shortTitle: 'İntegral ile Alan', description, summary: 'Grafiği doğru okuyarak x ekseniyle veya iki eğri arasında kalan alanı hangi integral düzeniyle bulacağınızı öğrenin.', readingTime: 9, level: 'Geometrik uygulama', keywords: ['integral ile alan hesabı', 'iki eğri arasındaki alan', 'AYT integral alan', 'belirli integral'], toc: [{ id: 'isaretli-alan', label: 'İşaretli alan' }, { id: 'x-ekseni', label: 'x ekseniyle alan' }, { id: 'iki-egri', label: 'İki eğri arası' }, { id: 'ornek', label: 'Çözümlü örnek' }, { id: 'strateji', label: 'Çözüm stratejisi' }], intro: ['Belirli integral bir fonksiyonun işaretli alanını verir; geometrik alan ise negatif olamaz. Bu ayrım, alan sorularında doğru integrali kurmanın anahtarıdır.', 'İşleme başlamadan önce grafiğin x eksenini kestiği noktaları ve hangi fonksiyonun üstte kaldığını belirlemek gerekir.'], related: { slug: 'integralde-degisken-degistirme', title: 'İntegralde Değişken Değiştirme', text: 'Farklı integral çözüm yöntemini pekiştirin' } };
export default function IntegralAreaArticlePage() { return <IntegralTopicArticle article={article}>
  <section id="isaretli-alan"><h2>İşaretli Alan ile Geometrik Alan Farkı</h2><p>Fonksiyon x ekseninin üstündeyken integral pozitiftir; altındayken negatiftir. Geometrik alan istendiğinde negatif kalan parçanın mutlak değeri alınır.</p><div className="article-math">Alan = ∫<sub>a</sub><sup>b</sup> |f(x)| dx</div></section>
  <section id="x-ekseni"><h2>Eğri ile x Ekseni Arasındaki Alan</h2><p>Önce f(x) = 0 denklemiyle eksen kesişimleri bulunur. Fonksiyon aralık boyunca pozitifse doğrudan integral alınır. İşaret değiştiriyorsa integral kök noktalarında parçalara ayrılır.</p><div className="article-math">Alan = |∫<sub>a</sub><sup>c</sup> f(x) dx| + |∫<sub>c</sub><sup>b</sup> f(x) dx|</div></section>
  <section id="iki-egri"><h2>İki Eğri Arasında Kalan Alan</h2><p>Kesişim noktaları integralin sınırlarını verir. Dikey dilimler kullanıldığında üstteki fonksiyondan alttaki çıkarılır.</p><div className="article-math">Alan = ∫<sub>a</sub><sup>b</sup> [üstteki − alttaki] dx</div><p>Eğrilerin sırası aralık içinde değişiyorsa integral kesişim noktasında parçalanmalıdır.</p></section>
  <section id="ornek"><h2>Adım Adım Çözümlü Örnek</h2><p>y = x ve y = x² eğrileri x = 0 ve x = 1 noktalarında kesişir. Bu aralıkta x, x²&apos;den büyüktür.</p><div className="article-math article-math-lines"><span>Alan = ∫<sub>0</sub><sup>1</sup> (x − x²) dx</span><span>= [x²/2 − x³/3]<sub>0</sub><sup>1</sup> = 1/2 − 1/3 = 1/6</span></div></section>
  <section id="strateji"><h2>Alan Soruları İçin Çözüm Stratejisi</h2><p><strong>1.</strong> Kesişimleri bulup basit bir grafik çizin. <strong>2.</strong> Alanın hangi aralıklarda olduğunu belirleyin. <strong>3.</strong> Üst–alt sırasını veya fonksiyonun işaretini kontrol edin. <strong>4.</strong> Gerekirse integrali parçalayın. <strong>5.</strong> Sonucun pozitif ve grafikle uyumlu olduğunu kontrol edin.</p></section>
 </IntegralTopicArticle>; }
