import Link from 'next/link';
import IntegralTopicArticle from '../../../components/public/IntegralTopicArticle';

const title = 'İntegral ile Alan Hesabı Nasıl Yapılır?';
const description = 'Eğri ile x ekseni ve iki eğri arasında kalan alanı integral kullanarak adım adım çözümlü örneklerle hesaplayın.';
export const metadata = {
  title, description, alternates: { canonical: '/makaleler/integral-ile-alan-hesabi' },
  keywords: ['integral ile alan hesabı', 'iki eğri arasındaki alan', 'belirli integral alan', 'AYT integral'],
  openGraph: { title, description, type: 'article', locale: 'tr_TR', siteName: 'MatAI', url: '/makaleler/integral-ile-alan-hesabi', images: [{ url: '/assets/articles/integral-alan.jpg', width: 1536, height: 1024, alt: title }], publishedTime: '2026-08-12T00:00:00+03:00', modifiedTime: '2026-08-19T00:00:00+03:00', authors: ['MatAI'] },
  twitter: { card: 'summary_large_image', title, description, images: ['/assets/articles/integral-alan.jpg'] },
};
const article = { slug: 'integral-ile-alan-hesabi', title, shortTitle: 'İntegral ile Alan', description, summary: 'Grafiği doğru okuyarak x ekseniyle veya iki eğri arasında kalan alanı hangi integral düzeniyle bulacağınızı üç farklı örnek üzerinden öğrenin.', readingTime: 12, level: 'Geometrik uygulama', dateModified: '2026-08-19T00:00:00+03:00', keywords: ['integral ile alan hesabı', 'iki eğri arasındaki alan', 'AYT integral alan', 'belirli integral'], toc: [{ id: 'isaretli-alan', label: 'İşaretli alan' }, { id: 'x-ekseni', label: 'x ekseniyle alan' }, { id: 'iki-egri', label: 'İki eğri arası' }, { id: 'ornekler', label: 'Çözümlü örnekler' }, { id: 'hatalar', label: 'Sık hatalar' }, { id: 'strateji', label: 'Çözüm stratejisi' }, { id: 'sss', label: 'Sık sorulanlar' }], intro: ['Belirli integral bir fonksiyonun işaretli alanını verir; geometrik alan ise negatif olamaz. Bu ayrım, alan sorularında doğru integrali kurmanın anahtarıdır.', 'İşleme başlamadan önce grafiğin x eksenini kestiği noktaları ve hangi fonksiyonun üstte kaldığını belirlemek gerekir. Aşağıdaki örneklerde pozitif bölgeyi, eksenin iki tarafına geçen bir eğriyi ve iki eğri arasındaki alanı ayrı ayrı ele alacağız.'], seriesLinks: [{ slug: 'belirli-integral-nedir', title: 'Belirli İntegral' }, { slug: 'turevin-geometrik-yorumu', title: 'Türevin Geometrik Yorumu' }], related: { slug: 'integralde-degisken-degistirme', title: 'İntegralde Değişken Değiştirme', text: 'Farklı integral çözüm yöntemini pekiştirin' } };
export default function IntegralAreaArticlePage() { return <IntegralTopicArticle article={article}>
  <section id="isaretli-alan"><h2>İşaretli Alan ile Geometrik Alan Farkı</h2><p>Belirli integral, x ekseninin üstündeki bölgeleri pozitif; altındaki bölgeleri negatif kabul eder. Bu nedenle birbirine eşit iki bölge integral sonucunda birbirini götürebilir. Soruda “integral değeri” isteniyorsa işaret korunur; “alan” isteniyorsa her parçanın büyüklüğü pozitif alınır.</p><div className="article-math">Geometrik alan = ∫<sub>a</sub><sup>b</sup> |f(x)| dx</div><p>Örneğin tek bir fonksiyon için integral sonucu sıfır çıkması, eğri ile eksen arasında hiç alan olmadığı anlamına gelmez. Pozitif ve negatif işaretli alanlar eşit büyüklükte olabilir.</p></section>
  <section id="x-ekseni"><h2>Eğri ile x Ekseni Arasındaki Alan</h2><p>Önce f(x) = 0 denklemiyle eğrinin x eksenini kestiği noktalar bulunur. Bu kökler, fonksiyonun işaret değiştirebileceği ve integralin parçalanması gerekebileceği sınırlardır.</p><p>Fonksiyon [a,b] aralığının tamamında pozitifse alan doğrudan belirli integraldir. Fonksiyon c noktasında ekseni geçiyorsa iki parça ayrı hesaplanır:</p><div className="article-math">Alan = |∫<sub>a</sub><sup>c</sup> f(x) dx| + |∫<sub>c</sub><sup>b</sup> f(x) dx|</div><p>Kökleri bulduktan sonra küçük bir işaret tablosu hazırlamak, mutlak değer hatalarını önler. Belirli integralin nasıl hesaplandığını tekrar etmek isterseniz <Link href="/makaleler/belirli-integral-nedir" className="article-inline-link">belirli integral konu anlatımına</Link> bakabilirsiniz.</p></section>
  <section id="iki-egri"><h2>İki Eğri Arasında Kalan Alan</h2><p>f(x) ve g(x) eğrilerinin kesişim noktaları f(x) = g(x) denklemiyle bulunur. Dikey dilimler kullanıldığında her x değeri için üstteki fonksiyondan alttaki çıkarılır.</p><div className="article-math">Alan = ∫<sub>a</sub><sup>b</sup> [üstteki − alttaki] dx</div><p>Hangi fonksiyonun üstte olduğunu yalnızca şekle bakarak varsaymayın. Kesişimler arasından seçilen bir test değerini iki fonksiyonda yerine koyun. Eğrilerin sırası aralık içinde değişiyorsa integrali o kesişim noktasında parçalayın.</p></section>
  <section id="ornekler"><h2>İntegral ile Alan Hesabı: 3 Çözümlü Örnek</h2><h3>Örnek 1: Tamamı x ekseninin üstünde kalan bölge</h3><p>f(x) = 4 − x² eğrisi ile x ekseni arasında, x = −2 ve x = 2 sınırlarındaki alanı bulalım. Fonksiyon bu aralıkta negatif olmadığı için integrali parçalamaya gerek yoktur.</p><div className="article-math article-math-lines"><span>Alan = ∫<sub>−2</sub><sup>2</sup> (4 − x²) dx</span><span>= [4x − x³/3]<sub>−2</sub><sup>2</sup> = 32/3 birim²</span></div><h3>Örnek 2: x eksenini geçen eğri</h3><p>f(x) = x² − 1 fonksiyonunun [−2,2] aralığında x ekseniyle sınırladığı toplam alanı bulalım. Kökler −1 ve 1&apos;dir. Fonksiyon dış aralıklarda pozitif, iki kök arasında negatiftir; bu yüzden üç parçanın mutlak değerlerini toplarız.</p><div className="article-math article-math-lines"><span>Alan = |∫<sub>−2</sub><sup>−1</sup> (x²−1)dx| + |∫<sub>−1</sub><sup>1</sup> (x²−1)dx| + |∫<sub>1</sub><sup>2</sup> (x²−1)dx|</span><span>= 4/3 + 4/3 + 4/3 = 4 birim²</span></div><h3>Örnek 3: İki eğri arasındaki alan</h3><p>y = x ve y = x² eğrileri x = 0 ve x = 1 noktalarında kesişir. Aradan seçilen x = 1/2 değeri için x, x²&apos;den büyük olduğundan üstteki eğri y = x&apos;tir.</p><div className="article-math article-math-lines"><span>Alan = ∫<sub>0</sub><sup>1</sup> (x − x²) dx</span><span>= [x²/2 − x³/3]<sub>0</sub><sup>1</sup> = 1/2 − 1/3 = 1/6 birim²</span></div></section>
  <section id="hatalar"><h2>Sık Yapılan Hatalar</h2><p><strong>İntegrali alan sanmak:</strong> Eğri eksenin altındaysa belirli integral negatif çıkabilir; geometrik alan negatif olamaz. <strong>Kesişimleri bulmadan işleme başlamak:</strong> Sınırlar yanlış seçildiğinde doğru integral kuralı bile yanlış sonuç verir. <strong>Alt–üst sırasını karıştırmak:</strong> İki eğri arasında “üstteki eksi alttaki” yazılmalıdır. <strong>Birimi unutmak:</strong> Alan sonuçları birim² ile ifade edilir.</p><p>İlkel fonksiyon bulma veya sabit katsayı konusunda zorlanıyorsanız önce <Link href="/makaleler/belirsiz-integral-nedir" className="article-inline-link">belirsiz integral kurallarını</Link> gözden geçirin.</p></section>
  <section id="strateji"><h2>Alan Soruları İçin Çözüm Stratejisi</h2><p><strong>1.</strong> Alanı sınırlayan eğrileri ve doğruları belirleyin. <strong>2.</strong> Eksen kesişimlerini veya eğrilerin ortak noktalarını bulun. <strong>3.</strong> Basit bir grafik ya da işaret tablosu çizin. <strong>4.</strong> Her aralıkta üst–alt sırasını ve fonksiyonun işaretini kontrol edin. <strong>5.</strong> Gerekirse integrali parçalara ayırın. <strong>6.</strong> Sonucun pozitif ve grafikle uyumlu olduğunu doğrulayın.</p></section>
  <section id="sss"><h2>İntegral ile Alan Hakkında Sık Sorulan Sorular</h2><h3>Alan hesabında neden mutlak değer kullanılır?</h3><p>Belirli integral eksenin altındaki bölgeyi negatif sayar. Geometrik alan büyüklük ifade ettiği için negatif parçalar mutlak değerle pozitife çevrilir.</p><h3>İki eğri arasında hangisi üstte nasıl anlaşılır?</h3><p>Önce kesişim noktaları bulunur. Bu noktaların arasından seçilen bir x değeri iki fonksiyonda hesaplanır; daha büyük sonucu veren fonksiyon o aralıkta üsttedir.</p><h3>İntegral sonucu sıfırken alan sıfırdan büyük olabilir mi?</h3><p>Evet. x ekseninin üstünde ve altında kalan işaretli alanlar eşit büyüklükteyse integral sıfır olur; fakat geometrik alan bu iki bölgenin pozitif toplamıdır.</p></section>
 </IntegralTopicArticle>; }
